//! Menu-bar / tray residency for the main desktop process.
//!
//! When `services.keepAppInMenuBar` is enabled, closing the main window hides
//! it instead of exiting. The tray provides Show Lattice, Quick Note, Settings,
//! and other actions (see [`crate::app_menu::build_tray_menu`]). This is an
//! in-process preference — not a login item or LSUIElement accessory.
//!
//! On macOS the tray uses a monochrome template mark (`tray-template.png`), not
//! the full-color Dock/app icon, so it matches system menu-bar styling.

use std::sync::atomic::{AtomicBool, Ordering};

use lattice_core::ensure_lattice_home;
use lattice_profile::{DesktopSettings, DESKTOP_SETTINGS_SPEC};
use serde::Serialize;
use tauri::{
    image::Image,
    tray::TrayIconBuilder,
    AppHandle, Emitter, Manager,
};

use crate::app_menu;

const TRAY_ID: &str = "lattice.main-tray";

static QUITTING: AtomicBool = AtomicBool::new(false);

#[derive(Clone, Serialize)]
struct QuickNoteOpenPayload {
    root: Option<String>,
}

/// True once Quit has been requested so CloseRequested does not re-hide.
pub fn is_quitting() -> bool {
    QUITTING.load(Ordering::SeqCst)
}

pub fn request_quit(app: &AppHandle) {
    QUITTING.store(true, Ordering::SeqCst);
    app.exit(0);
}

pub fn keep_app_in_menu_bar() -> bool {
    ensure_lattice_home()
        .ok()
        .and_then(|home| {
            home.settings_store()
                .load::<DesktopSettings>(DESKTOP_SETTINGS_SPEC)
                .ok()
                .map(|loaded| loaded.value.services.keep_app_in_menu_bar)
        })
        .unwrap_or(false)
}

/// Whether closing the main window should hide instead of exiting.
pub fn should_hide_main_on_close(keep_in_menu_bar: bool, quitting: bool) -> bool {
    keep_in_menu_bar && !quitting
}

pub fn show_main_window(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

pub fn show_quick_note(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("quick-note") {
        let _ = window.show();
        let _ = window.set_focus();
        let _ = window.emit(
            "quick-note-open",
            QuickNoteOpenPayload { root: None },
        );
    }
}

/// Menu-bar mark: black + alpha, regenerated by `site/scripts/generate-mark.mjs`.
/// Distinct from the full-color Dock icon in `icons/icon.*`.
fn tray_template_icon() -> tauri::Result<Image<'static>> {
    Image::from_bytes(include_bytes!("../icons/tray-template.png"))
}

pub fn install_tray(app: &AppHandle) -> tauri::Result<()> {
    let menu = app_menu::build_tray_menu(app)?;

    let mut builder = TrayIconBuilder::with_id(TRAY_ID)
        .menu(&menu)
        .tooltip("Lattice")
        .on_menu_event(|app, event| {
            app_menu::handle_action(app, event.id().as_ref());
        });

    #[cfg(target_os = "macos")]
    {
        match tray_template_icon() {
            Ok(icon) => {
                // Template mode: system tints black+alpha to match the menu bar.
                builder = builder.icon(icon).icon_as_template(true);
            }
            Err(_) => {
                // Degraded fallback — prefer a visible tray over none.
                if let Some(icon) = app.default_window_icon() {
                    builder = builder.icon(icon.clone());
                }
            }
        }
        // Menu on left click matches menu-bar residency expectations.
        builder = builder.show_menu_on_left_click(true);
    }

    // No template tinting off macOS; black+alpha would vanish on dark panels.
    #[cfg(not(target_os = "macos"))]
    {
        if let Some(icon) = app.default_window_icon() {
            builder = builder.icon(icon.clone());
        } else if let Ok(icon) = tray_template_icon() {
            builder = builder.icon(icon);
        }
    }

    let _tray = builder.build(app)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hide_on_close_requires_preference_and_not_quitting() {
        assert!(should_hide_main_on_close(true, false));
        assert!(!should_hide_main_on_close(true, true));
        assert!(!should_hide_main_on_close(false, false));
        assert!(!should_hide_main_on_close(false, true));
    }

    #[test]
    fn tray_template_icon_decodes() {
        let icon = tray_template_icon().expect("tray-template.png must decode");
        assert_eq!(icon.width(), 64);
        assert_eq!(icon.height(), 64);
        assert!(!icon.rgba().is_empty());
    }
}
