//! Menu-bar / tray residency for the main desktop process.
//!
//! When `services.keepAppInMenuBar` is enabled, closing the main window hides
//! it instead of exiting. The tray provides Show Lattice, Quick Note, Settings,
//! and other actions (see [`crate::app_menu::build_tray_menu`]). This is an
//! in-process preference — not a login item or LSUIElement accessory.
//!
//! On macOS the tray uses a monochrome template mark (`tray-template.png`), not
//! the full-color Dock/app icon, so it matches system menu-bar styling.
//!
//! Running jobs merge desktop in-process [`WorkflowState`] with daemon-owned
//! schedule runs (HTTP job API when available, else on-disk `running` records).

use std::collections::HashSet;
use std::path::Path;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use lattice_commands::{
    execution_summary_from_record, list_all_workflow_runs, ExecutionStatus, CANCEL_OWNER_DAEMON,
    CANCEL_OWNER_DESKTOP, CANCEL_OWNER_NONE,
};
use lattice_core::ensure_lattice_home;
use lattice_handlers::QuickNotePrepared;
use lattice_profile::{DesktopSettings, DESKTOP_SETTINGS_SPEC};
use serde::Serialize;
use tauri::{image::Image, tray::TrayIconBuilder, AppHandle, Emitter, Manager};

use crate::app_menu;
use crate::workspace_root;
use crate::workflow::{self, WorkflowState};

const TRAY_ID: &str = "lattice.main-tray";
const ENV_AUTH_TOKEN: &str = "LATTICE_AUTH_TOKEN";
const ENV_API_PORT: &str = "LATTICE_API_PORT";
const DEFAULT_API_PORT: u16 = 18787;

static QUITTING: AtomicBool = AtomicBool::new(false);

#[derive(Clone, Serialize)]
struct QuickNoteOpenPayload {
    root: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    prepared: Option<QuickNotePrepared>,
}

/// True once Quit has been requested so CloseRequested does not re-hide.
pub fn is_quitting() -> bool {
    QUITTING.load(Ordering::SeqCst)
}

pub fn request_quit(app: &AppHandle) {
    QUITTING.store(true, Ordering::SeqCst);
    app.exit(0);
}

pub fn keep_app_in_menu_bar() -> bool {
    ensure_lattice_home()
        .ok()
        .and_then(|home| {
            home.settings_store()
                .load::<DesktopSettings>(DESKTOP_SETTINGS_SPEC)
                .ok()
                .map(|loaded| loaded.value.services.keep_app_in_menu_bar)
        })
        .unwrap_or(false)
}

/// Whether closing the main window should hide instead of exiting.
pub fn should_hide_main_on_close(keep_in_menu_bar: bool, quitting: bool) -> bool {
    keep_in_menu_bar && !quitting
}

pub fn show_main_window(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

/// Open Quick Note from the menu bar / tray via the semantic command core.
pub fn show_quick_note(app: &AppHandle) {
    open_quick_note(app, None);
}

pub fn open_quick_note(app: &AppHandle, requested_root: Option<String>) {
    let app = app.clone();
    std::thread::spawn(move || {
        let root = match requested_root.filter(|value| !value.trim().is_empty()) {
            Some(root) => Some(root),
            None => workspace_root::resolve_default_workspace_root(),
        };
        let prepared = root
            .as_ref()
            .and_then(|value| lattice_handlers::prepare_quick_note(value.clone()).ok());
        if let Some(window) = app.get_webview_window("quick-note") {
            let _ = window.show();
            let _ = window.set_focus();
            let _ = window.emit(
                "quick-note-open",
                QuickNoteOpenPayload {
                    root: prepared
                        .as_ref()
                        .map(|note| note.root.clone())
                        .or(root),
                    prepared,
                },
            );
        }
    });
}

/// Menu-bar mark: black + alpha, regenerated by `site/scripts/generate-mark.mjs`.
/// Distinct from the full-color Dock icon in `icons/icon.*`.
fn tray_template_icon() -> tauri::Result<Image<'static>> {
    Image::from_bytes(include_bytes!("../icons/tray-template.png"))
}

pub fn install_tray(app: &AppHandle) -> tauri::Result<()> {
    let menu = app_menu::build_tray_menu(app, &[])?;

    let mut builder = TrayIconBuilder::with_id(TRAY_ID)
        .menu(&menu)
        .tooltip("Lattice")
        .on_menu_event(|app, event| {
            app_menu::handle_action(app, event.id().as_ref());
        });

    #[cfg(target_os = "macos")]
    {
        match tray_template_icon() {
            Ok(icon) => {
                // Template mode: system tints black+alpha to match the menu bar.
                builder = builder.icon(icon).icon_as_template(true);
            }
            Err(_) => {
                // Degraded fallback — prefer a visible tray over none.
                if let Some(icon) = app.default_window_icon() {
                    builder = builder.icon(icon.clone());
                }
            }
        }
        // Menu on left click matches menu-bar residency expectations.
        builder = builder.show_menu_on_left_click(true);
    }

    // No template tinting off macOS; black+alpha would vanish on dark panels.
    #[cfg(not(target_os = "macos"))]
    {
        if let Some(icon) = app.default_window_icon() {
            builder = builder.icon(icon.clone());
        } else if let Ok(icon) = tray_template_icon() {
            builder = builder.icon(icon);
        }
    }

    let _tray = builder.build(app)?;
    refresh_from_workflows(app);
    Ok(())
}

fn tray_label(workflow_path: &str) -> String {
    let file_name = Path::new(workflow_path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or(workflow_path);
    file_name
        .strip_suffix(".workflow.yaml")
        .or_else(|| file_name.strip_suffix(".workflow.yml"))
        .unwrap_or(file_name)
        .to_string()
}

fn desktop_running_jobs(app: &AppHandle) -> Vec<app_menu::TrayRunningJob> {
    let Some(state) = app.try_state::<WorkflowState>() else {
        return Vec::new();
    };
    workflow::running_workflows(&state)
        .into_iter()
        .map(|job| app_menu::TrayRunningJob {
            execution_id: job.execution_id,
            workflow_path: job.workflow_path,
            label: job.label,
            workspace_root: job.workspace_root,
            cancel_owner: job.cancel_owner,
            cancellable: job.cancellable,
        })
        .collect()
}

fn disk_daemon_running_jobs(workspace_root: &Path) -> Vec<app_menu::TrayRunningJob> {
    let Ok(runs) = list_all_workflow_runs(workspace_root, 32) else {
        return Vec::new();
    };
    runs.into_iter()
        .filter(|record| record.execution.status == ExecutionStatus::Running)
        .filter(|record| record.trigger == "schedule")
        .map(|record| {
            let summary =
                execution_summary_from_record(workspace_root, &record, CANCEL_OWNER_DAEMON);
            app_menu::TrayRunningJob {
                execution_id: summary.execution_id,
                workflow_path: summary.resource_path.clone(),
                label: tray_label(&summary.resource_path),
                workspace_root: summary.workspace_root,
                cancel_owner: CANCEL_OWNER_DAEMON.into(),
                cancellable: summary.cancellable,
            }
        })
        .collect()
}

fn http_daemon_running_jobs() -> Vec<app_menu::TrayRunningJob> {
    let token = match std::env::var(ENV_AUTH_TOKEN) {
        Ok(token) if !token.trim().is_empty() => token,
        _ => return Vec::new(),
    };
    let port = std::env::var(ENV_API_PORT)
        .ok()
        .and_then(|value| value.parse::<u16>().ok())
        .filter(|port| *port != 0)
        .unwrap_or(DEFAULT_API_PORT);

    let url = format!("http://127.0.0.1:{port}/v1/jobs/list_active");
    let response = match ureq::post(&url)
        .set("authorization", &format!("Bearer {token}"))
        .set("content-type", "application/json")
        .timeout(Duration::from_millis(400))
        .send_string("{}")
    {
        Ok(response) => response,
        Err(_) => return Vec::new(),
    };
    #[derive(serde::Deserialize)]
    struct ListBody {
        jobs: Vec<lattice_commands::ExecutionSummary>,
    }
    let body: ListBody = match response
        .into_string()
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
    {
        Some(body) => body,
        None => return Vec::new(),
    };
    body.jobs
        .into_iter()
        .filter(|job| job.status == ExecutionStatus::Running)
        .map(|job| app_menu::TrayRunningJob {
            execution_id: job.execution_id,
            workflow_path: job.resource_path.clone(),
            label: tray_label(&job.resource_path),
            workspace_root: job.workspace_root,
            cancel_owner: if job.cancel_owner.is_empty() {
                CANCEL_OWNER_DAEMON.into()
            } else {
                job.cancel_owner
            },
            cancellable: job.cancellable,
        })
        .collect()
}

fn tray_running_jobs(app: &AppHandle) -> Vec<app_menu::TrayRunningJob> {
    let mut jobs = desktop_running_jobs(app);
    let mut seen: HashSet<String> = jobs.iter().map(|job| job.execution_id.clone()).collect();

    for job in http_daemon_running_jobs() {
        if seen.insert(job.execution_id.clone()) {
            jobs.push(job);
        }
    }

    if let Some(root) = workflow_workspace_root(app) {
        for job in disk_daemon_running_jobs(Path::new(&root)) {
            if seen.insert(job.execution_id.clone()) {
                jobs.push(job);
            }
        }
    }

    jobs.sort_by(|left, right| right.execution_id.cmp(&left.execution_id));
    jobs
}

fn workflow_workspace_root(app: &AppHandle) -> Option<String> {
    app.try_state::<WorkflowState>()
        .and_then(|state| workflow::active_workspace_root(&state))
        .map(|root| root.to_string_lossy().into_owned())
}

/// Rebuild the tray menu and tooltip from live workflow execution state.
pub fn refresh_from_workflows(app: &AppHandle) {
    let running = tray_running_jobs(app);
    let menu = match app_menu::build_tray_menu(app, &running) {
        Ok(menu) => menu,
        Err(err) => {
            eprintln!("lattice: failed to build tray menu: {err}");
            return;
        }
    };
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    if let Err(err) = tray.set_menu(Some(menu)) {
        eprintln!("lattice: failed to update tray menu: {err}");
    }
    let tooltip = if running.is_empty() {
        "Lattice".to_string()
    } else if running.len() == 1 {
        "Lattice — 1 workflow running".to_string()
    } else {
        format!("Lattice — {} workflows running", running.len())
    };
    if let Err(err) = tray.set_tooltip(Some(tooltip)) {
        eprintln!("lattice: failed to update tray tooltip: {err}");
    }
}

/// Workspace root + workflow path for the newest running execution, if any.
pub fn latest_running_workflow(app: &AppHandle) -> Option<(String, String)> {
    let job = tray_running_jobs(app).into_iter().next()?;
    let root = if job.workspace_root.is_empty() {
        workflow_workspace_root(app)?
    } else {
        job.workspace_root
    };
    Some((root, job.workflow_path))
}

/// Workspace root + workflow path for a specific running execution id.
pub fn running_workflow_by_id(app: &AppHandle, execution_id: &str) -> Option<(String, String)> {
    let job = tray_running_jobs(app)
        .into_iter()
        .find(|job| job.execution_id == execution_id)?;
    let root = if job.workspace_root.is_empty() {
        workflow_workspace_root(app)?
    } else {
        job.workspace_root
    };
    Some((root, job.workflow_path))
}

/// Cancel a running job, routing to desktop or daemon owner.
pub fn cancel_running_job(app: &AppHandle, execution_id: &str) -> Result<(), String> {
    let job = tray_running_jobs(app)
        .into_iter()
        .find(|job| job.execution_id == execution_id)
        .ok_or_else(|| format!("unknown running job: {execution_id}"))?;
    if !job.cancellable {
        return Err(format!("job {execution_id} is not cancellable"));
    }
    match job.cancel_owner.as_str() {
        CANCEL_OWNER_DESKTOP => {
            let state = app
                .try_state::<WorkflowState>()
                .ok_or_else(|| "workflow state unavailable".to_string())?;
            workflow::request_cancel(&state, execution_id)
        }
        CANCEL_OWNER_DAEMON => cancel_daemon_job(execution_id),
        CANCEL_OWNER_NONE => Err(format!("job {execution_id} has no cancel owner")),
        other => Err(format!("unknown cancel owner '{other}' for {execution_id}")),
    }
}

fn cancel_daemon_job(execution_id: &str) -> Result<(), String> {
    let token = std::env::var(ENV_AUTH_TOKEN)
        .map_err(|_| format!("{ENV_AUTH_TOKEN} required to cancel daemon jobs"))?;
    let port = std::env::var(ENV_API_PORT)
        .ok()
        .and_then(|value| value.parse::<u16>().ok())
        .filter(|port| *port != 0)
        .unwrap_or(DEFAULT_API_PORT);
    let url = format!("http://127.0.0.1:{port}/v1/jobs/cancel");
    let body = serde_json::json!({ "executionId": execution_id }).to_string();
    let response = ureq::post(&url)
        .set("authorization", &format!("Bearer {token}"))
        .set("content-type", "application/json")
        .timeout(Duration::from_secs(2))
        .send_string(&body)
        .map_err(|err| format!("daemon cancel failed: {err}"))?;
    if response.status() >= 300 {
        let status = response.status();
        let text = response.into_string().unwrap_or_default();
        return Err(format!("daemon cancel HTTP {status}: {text}"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hide_on_close_requires_preference_and_not_quitting() {
        assert!(should_hide_main_on_close(true, false));
        assert!(!should_hide_main_on_close(true, true));
        assert!(!should_hide_main_on_close(false, false));
        assert!(!should_hide_main_on_close(false, true));
    }

    #[test]
    fn tray_template_icon_decodes() {
        let icon = tray_template_icon().expect("tray-template.png must decode");
        assert_eq!(icon.width(), 64);
        assert_eq!(icon.height(), 64);
        assert!(!icon.rgba().is_empty());
    }
}
