/**
 * Browser-demo theme catalog — builtins only, prefs in localStorage.
 * Mirrors Tauri `list_themes` / `set_theme` enough for palette UX.
 */

import slateCss from "../theme-tokens.css?raw";

import {
  detectSystemAppearance,
  type ResolvedThemePayload,
  type ThemeCatalogPayload,
} from "./apply";

const DEMO_PREFS_KEY = "lattice.theme.demoPrefs";

interface DemoPrefs {
  mode: "fixed" | "auto";
  theme: string;
  pair: { dark: string; light: string };
}

const DEFAULT_PREFS: DemoPrefs = {
  mode: "fixed",
  theme: "lattice-slate",
  pair: { dark: "lattice-slate", light: "lattice-paper" },
};

/** Paper light tokens — kept in sync with themes/lattice-paper.theme.yaml roles. */
const PAPER_VARS: Record<string, string> = {
  "--lt-bg": "#f4f6fa",
  "--lt-bg-raise": "#eef1f7",
  "--lt-panel": "#ffffff",
  "--lt-slate": "#5a6b86",
  "--lt-text": "#121822",
  "--lt-text-soft": "#3a4558",
  "--lt-muted": "#6b778c",
  "--lt-faint": "#8b96a8",
  "--lt-accent": "#c47a0a",
  "--lt-accent-bright": "#a86408",
  "--lt-accent-deep": "#8a5206",
  "--lt-danger": "#b42318",
  "--lt-shadow": "#0a0d13",
  "--lt-on-accent": "#fff8ef",
  "--lt-surface": "var(--lt-panel)",
  "--lt-hover": "color-mix(in oklch, var(--lt-slate) 7%, transparent)",
  "--lt-line": "color-mix(in oklch, var(--lt-slate) 12%, transparent)",
  "--lt-line-strong": "color-mix(in oklch, var(--lt-slate) 22%, transparent)",
  "--lt-border": "color-mix(in oklch, var(--lt-slate) 18%, transparent)",
  "--lt-accent-wash": "color-mix(in oklch, var(--lt-accent) 10%, transparent)",
  "--lt-accent-glow": "color-mix(in oklch, var(--lt-accent) 55%, transparent)",
  "--lt-accent-glow-soft": "color-mix(in oklch, var(--lt-accent) 35%, transparent)",
  "--lt-accent-glow-mid": "color-mix(in oklch, var(--lt-accent) 22%, transparent)",
  "--lt-accent-glow-strong": "color-mix(in oklch, var(--lt-accent) 45%, transparent)",
  "--lt-accent-underline": "color-mix(in oklch, var(--lt-accent) 35%, transparent)",
  "--lt-node-dot": "color-mix(in oklch, var(--lt-slate) 26%, transparent)",
  "--lt-node-dot-soft": "color-mix(in oklch, var(--lt-slate) 20%, transparent)",
  "--lt-scrim": "color-mix(in oklch, var(--lt-bg) 60%, transparent)",
  "--lt-scrim-deep": "color-mix(in oklch, var(--lt-bg) 72%, #06080c)",
  "--lt-shadow-md": "color-mix(in oklch, var(--lt-shadow) 35%, transparent)",
  "--lt-shadow-lg": "color-mix(in oklch, var(--lt-shadow) 45%, transparent)",
  "--lt-font-display": '"Fraunces Variable", "Fraunces", Georgia, serif',
  "--lt-font-ui": '"Space Grotesk Variable", "Space Grotesk", system-ui, sans-serif',
  "--lt-font-mono":
    '"JetBrains Mono Variable", "JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
  "--lt-radius": "9px",
  "--lt-radius-sm": "6px",
  "--lt-radius-lg": "14px",
  "--lt-grid": "34px",
  "--lt-titlebar": "38px",
  "--lt-max-width": "1140px",
  "--l-bg": "var(--lt-bg)",
  "--l-bg-2": "var(--lt-bg-raise)",
  "--l-panel": "var(--lt-panel)",
  "--l-panel-2": "var(--lt-panel)",
  "--l-line": "var(--lt-line)",
  "--l-line-strong": "var(--lt-line-strong)",
  "--l-border": "var(--lt-border)",
  "--l-text": "var(--lt-text)",
  "--l-text-soft": "var(--lt-text-soft)",
  "--l-muted": "var(--lt-muted)",
  "--l-faint": "var(--lt-faint)",
  "--l-amber": "var(--lt-accent)",
  "--l-amber-bright": "var(--lt-accent-bright)",
  "--l-amber-deep": "var(--lt-accent-deep)",
  "--l-amber-glow": "var(--lt-accent-glow)",
  "--l-amber-wash": "var(--lt-accent-wash)",
  "--l-font-display": "var(--lt-font-display)",
  "--l-font-body": "var(--lt-font-ui)",
  "--l-font-mono": "var(--lt-font-mono)",
  "--l-maxw": "var(--lt-max-width)",
  "--l-radius": "var(--lt-radius-lg)",
  "--l-radius-sm": "var(--lt-radius)",
  "--l-grid-size": "var(--lt-grid)",
};

function parseCssRootVars(css: string): Record<string, string> {
  const vars: Record<string, string> = {};
  const re = /(--[a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css))) {
    vars[m[1]] = m[2].trim();
  }
  return vars;
}

const SLATE_VARS = parseCssRootVars(slateCss);

function variantVars(overrides: Record<string, string>): Record<string, string> {
  return { ...SLATE_VARS, ...overrides };
}

const DEMO_THEMES: Record<
  string,
  { name: string; appearance: "dark" | "light"; vars: Record<string, string> }
> = {
  "lattice-slate": { name: "Lattice Slate", appearance: "dark", vars: SLATE_VARS },
  "lattice-paper": { name: "Lattice Paper", appearance: "light", vars: PAPER_VARS },
  "lattice-carbon": {
    name: "Lattice Carbon",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#090a0c",
      "--lt-bg-raise": "#101215",
      "--lt-panel": "#171a1e",
      "--lt-slate": "#98a0aa",
      "--lt-text": "#f0f2f4",
      "--lt-text-soft": "#c5c9ce",
      "--lt-muted": "#8e959e",
      "--lt-faint": "#626973",
      "--lt-accent": "#ff7a45",
      "--lt-accent-bright": "#ffb08f",
      "--lt-accent-deep": "#d95222",
      "--lt-danger": "#ff806f",
      "--lt-on-accent": "#240b03",
      "--lt-radius": "7px",
      "--lt-radius-sm": "5px",
      "--lt-radius-lg": "12px",
      "--lt-grid": "32px",
    }),
  },
  "lattice-fjord": {
    name: "Lattice Fjord",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#071217",
      "--lt-bg-raise": "#0b1a21",
      "--lt-panel": "#10252d",
      "--lt-slate": "#88a8b3",
      "--lt-text": "#e8f3f4",
      "--lt-text-soft": "#b8cdd1",
      "--lt-muted": "#7f9ba3",
      "--lt-faint": "#536f78",
      "--lt-accent": "#42d6bd",
      "--lt-accent-bright": "#9aefdf",
      "--lt-accent-deep": "#159b89",
      "--lt-danger": "#ff8e82",
      "--lt-on-accent": "#04201c",
      "--lt-radius": "10px",
      "--lt-radius-sm": "7px",
      "--lt-radius-lg": "15px",
      "--lt-grid": "36px",
    }),
  },
  "lattice-ultraviolet": {
    name: "Lattice Ultraviolet",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#0d0916",
      "--lt-bg-raise": "#151023",
      "--lt-panel": "#1d1730",
      "--lt-slate": "#a199bd",
      "--lt-text": "#f1edfa",
      "--lt-text-soft": "#cbc3df",
      "--lt-muted": "#958aa9",
      "--lt-faint": "#695f7c",
      "--lt-accent": "#b08cff",
      "--lt-accent-bright": "#d8c5ff",
      "--lt-accent-deep": "#7651d5",
      "--lt-danger": "#ff8caa",
      "--lt-on-accent": "#180c2b",
      "--lt-radius": "11px",
      "--lt-radius-sm": "7px",
      "--lt-radius-lg": "17px",
    }),
  },
  "lattice-blueprint": {
    name: "Lattice Blueprint",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#07182b",
      "--lt-bg-raise": "#0b2139",
      "--lt-panel": "#102b49",
      "--lt-slate": "#84a7ca",
      "--lt-text": "#edf5ff",
      "--lt-text-soft": "#bfd3e8",
      "--lt-muted": "#88a6c2",
      "--lt-faint": "#587797",
      "--lt-accent": "#ffc857",
      "--lt-accent-bright": "#ffe3a0",
      "--lt-accent-deep": "#d99a20",
      "--lt-danger": "#ff9b8b",
      "--lt-on-accent": "#251801",
      "--lt-radius": "5px",
      "--lt-radius-sm": "3px",
      "--lt-radius-lg": "9px",
      "--lt-grid": "28px",
    }),
  },
  "lattice-vellum": {
    name: "Lattice Vellum",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f3ecdc",
      "--lt-bg-raise": "#ebe1ce",
      "--lt-panel": "#fbf7ed",
      "--lt-slate": "#766f66",
      "--lt-text": "#2b241d",
      "--lt-text-soft": "#554b40",
      "--lt-muted": "#786d61",
      "--lt-faint": "#9a8d7d",
      "--lt-accent": "#9f3f35",
      "--lt-accent-bright": "#7d2d27",
      "--lt-accent-deep": "#6b211d",
      "--lt-danger": "#a62f2a",
      "--lt-on-accent": "#fff8ee",
      "--lt-radius": "8px",
      "--lt-radius-sm": "5px",
      "--lt-radius-lg": "12px",
    }),
  },
  "lattice-ember": {
    name: "Lattice Ember",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#120b09",
      "--lt-bg-raise": "#1a100d",
      "--lt-panel": "#221512",
      "--lt-slate": "#b39a90",
      "--lt-text": "#f6ece8",
      "--lt-text-soft": "#d8c5be",
      "--lt-muted": "#a08a82",
      "--lt-faint": "#6f5d56",
      "--lt-accent": "#ff6b4a",
      "--lt-accent-bright": "#ffa38c",
      "--lt-accent-deep": "#cc4526",
      "--lt-danger": "#ff7b9d",
      "--lt-on-accent": "#2b0d04",
    }),
  },
  "lattice-moss": {
    name: "Lattice Moss",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#0b120c",
      "--lt-bg-raise": "#101a12",
      "--lt-panel": "#16241a",
      "--lt-slate": "#93ab97",
      "--lt-text": "#eaf4ec",
      "--lt-text-soft": "#c2d4c6",
      "--lt-muted": "#8aa290",
      "--lt-faint": "#5c7263",
      "--lt-accent": "#8fd460",
      "--lt-accent-bright": "#c0eda0",
      "--lt-accent-deep": "#5aa32f",
      "--lt-danger": "#ff9d8a",
      "--lt-on-accent": "#10230a",
    }),
  },
  "lattice-midnight": {
    name: "Lattice Midnight",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#060913",
      "--lt-bg-raise": "#0a0f1f",
      "--lt-panel": "#101730",
      "--lt-slate": "#8a95c4",
      "--lt-text": "#e9edfa",
      "--lt-text-soft": "#bcc5e0",
      "--lt-muted": "#8791b4",
      "--lt-faint": "#59628a",
      "--lt-accent": "#5aa9ff",
      "--lt-accent-bright": "#9cccff",
      "--lt-accent-deep": "#2d7dd6",
      "--lt-danger": "#ff8ca0",
      "--lt-on-accent": "#06121f",
    }),
  },
  "lattice-copper": {
    name: "Lattice Copper",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#100d0b",
      "--lt-bg-raise": "#171310",
      "--lt-panel": "#1f1a15",
      "--lt-slate": "#b3a494",
      "--lt-text": "#f5efe8",
      "--lt-text-soft": "#d7cdc0",
      "--lt-muted": "#a2968a",
      "--lt-faint": "#6f665c",
      "--lt-accent": "#e08d49",
      "--lt-accent-bright": "#ffc08a",
      "--lt-accent-deep": "#b0661f",
      "--lt-danger": "#ff8f8f",
      "--lt-on-accent": "#241203",
    }),
  },
  "lattice-rosewood": {
    name: "Lattice Rosewood",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#140b10",
      "--lt-bg-raise": "#1c1017",
      "--lt-panel": "#26161f",
      "--lt-slate": "#bb98a8",
      "--lt-text": "#f8ecf1",
      "--lt-text-soft": "#dcc4ce",
      "--lt-muted": "#a68a97",
      "--lt-faint": "#745e68",
      "--lt-accent": "#f26d8f",
      "--lt-accent-bright": "#ffa8bd",
      "--lt-accent-deep": "#c04165",
      "--lt-danger": "#ff9a6b",
      "--lt-on-accent": "#2b0713",
    }),
  },
  "lattice-graphite": {
    name: "Lattice Graphite",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#0c0d0f",
      "--lt-bg-raise": "#121417",
      "--lt-panel": "#191c20",
      "--lt-slate": "#9aa4ae",
      "--lt-text": "#eef1f4",
      "--lt-text-soft": "#c6ccd2",
      "--lt-muted": "#8c959e",
      "--lt-faint": "#5e666e",
      "--lt-accent": "#bfe34d",
      "--lt-accent-bright": "#dcf28f",
      "--lt-accent-deep": "#8fb61e",
      "--lt-danger": "#ff8d8d",
      "--lt-on-accent": "#1a2003",
    }),
  },
  "lattice-glacier": {
    name: "Lattice Glacier",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f2f7fa",
      "--lt-bg-raise": "#e8f0f6",
      "--lt-panel": "#ffffff",
      "--lt-slate": "#5d7286",
      "--lt-text": "#10222e",
      "--lt-text-soft": "#38505f",
      "--lt-muted": "#6a8090",
      "--lt-faint": "#8fa2af",
      "--lt-accent": "#0b7fc4",
      "--lt-accent-bright": "#086298",
      "--lt-accent-deep": "#064a74",
      "--lt-danger": "#c22f2f",
      "--lt-shadow": "#0a0d13",
      "--lt-on-accent": "#f2faff",
    }),
  },
  "lattice-sandstone": {
    name: "Lattice Sandstone",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f7f1e6",
      "--lt-bg-raise": "#f0e7d6",
      "--lt-panel": "#fdfaf3",
      "--lt-slate": "#837465",
      "--lt-text": "#2b2118",
      "--lt-text-soft": "#55483a",
      "--lt-muted": "#7b6d5e",
      "--lt-faint": "#9c8f80",
      "--lt-accent": "#c05621",
      "--lt-accent-bright": "#9c3f12",
      "--lt-accent-deep": "#7c300b",
      "--lt-danger": "#b3261e",
      "--lt-shadow": "#0a0d13",
      "--lt-on-accent": "#fff6ee",
    }),
  },
  "lattice-orchid": {
    name: "Lattice Orchid",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f7f4fb",
      "--lt-bg-raise": "#efeaf7",
      "--lt-panel": "#ffffff",
      "--lt-slate": "#756b8c",
      "--lt-text": "#211a30",
      "--lt-text-soft": "#473d5c",
      "--lt-muted": "#6f6585",
      "--lt-faint": "#948bab",
      "--lt-accent": "#7a3ff2",
      "--lt-accent-bright": "#5f28cc",
      "--lt-accent-deep": "#4a1da6",
      "--lt-danger": "#c22f52",
      "--lt-shadow": "#0a0d13",
      "--lt-on-accent": "#f7f2ff",
    }),
  },
  "lattice-meadow": {
    name: "Lattice Meadow",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f3f8f1",
      "--lt-bg-raise": "#e9f2e6",
      "--lt-panel": "#ffffff",
      "--lt-slate": "#667f64",
      "--lt-text": "#17251a",
      "--lt-text-soft": "#3c5242",
      "--lt-muted": "#66806c",
      "--lt-faint": "#8ba28f",
      "--lt-accent": "#2e7d32",
      "--lt-accent-bright": "#1f6023",
      "--lt-accent-deep": "#164a1a",
      "--lt-danger": "#b3392b",
      "--lt-shadow": "#0a0d13",
      "--lt-on-accent": "#f2fff3",
    }),
  },
  "lattice-porcelain": {
    name: "Lattice Porcelain",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f4f7f8",
      "--lt-bg-raise": "#e9eff1",
      "--lt-panel": "#ffffff",
      "--lt-slate": "#61747b",
      "--lt-text": "#182326",
      "--lt-text-soft": "#405157",
      "--lt-muted": "#687b81",
      "--lt-faint": "#91a0a5",
      "--lt-accent": "#d1432f",
      "--lt-accent-bright": "#ad2f20",
      "--lt-accent-deep": "#842319",
      "--lt-danger": "#b42335",
      "--lt-shadow": "#101719",
      "--lt-on-accent": "#fff8f5",
      "--lt-radius": "8px",
      "--lt-radius-sm": "5px",
      "--lt-radius-lg": "13px",
      "--lt-grid": "32px",
    }),
  },
  "lattice-matcha": {
    name: "Lattice Matcha",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f2f3e8",
      "--lt-bg-raise": "#e8eadb",
      "--lt-panel": "#fbfcf5",
      "--lt-slate": "#6d7459",
      "--lt-text": "#24291d",
      "--lt-text-soft": "#4b523d",
      "--lt-muted": "#737b62",
      "--lt-faint": "#989e87",
      "--lt-accent": "#a76f16",
      "--lt-accent-bright": "#85550d",
      "--lt-accent-deep": "#624008",
      "--lt-danger": "#b34032",
      "--lt-shadow": "#11140d",
      "--lt-on-accent": "#fff8e8",
      "--lt-radius": "10px",
      "--lt-radius-sm": "7px",
      "--lt-radius-lg": "15px",
      "--lt-grid": "36px",
    }),
  },
  "lattice-solar-flare": {
    name: "Lattice Solar Flare",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#080b14",
      "--lt-bg-raise": "#0d1220",
      "--lt-panel": "#141b2c",
      "--lt-slate": "#7d8ca8",
      "--lt-text": "#edf1f8",
      "--lt-text-soft": "#c0c9d9",
      "--lt-muted": "#8793a9",
      "--lt-faint": "#59667e",
      "--lt-accent": "#f6c445",
      "--lt-accent-bright": "#ffe08a",
      "--lt-accent-deep": "#c68d14",
      "--lt-danger": "#ff756f",
      "--lt-shadow": "#03050a",
      "--lt-on-accent": "#211600",
      "--lt-radius": "7px",
      "--lt-radius-sm": "4px",
      "--lt-radius-lg": "12px",
      "--lt-grid": "30px",
    }),
  },
  "lattice-tidepool": {
    name: "Lattice Tidepool",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#061315",
      "--lt-bg-raise": "#0a1c1f",
      "--lt-panel": "#10272b",
      "--lt-slate": "#7c9fa2",
      "--lt-text": "#e7f2f1",
      "--lt-text-soft": "#b9cfce",
      "--lt-muted": "#7f9c9d",
      "--lt-faint": "#526f72",
      "--lt-accent": "#ff826f",
      "--lt-accent-bright": "#ffb2a5",
      "--lt-accent-deep": "#cb5846",
      "--lt-danger": "#ff6f91",
      "--lt-shadow": "#02090a",
      "--lt-on-accent": "#2a0d08",
      "--lt-radius": "11px",
      "--lt-radius-sm": "7px",
      "--lt-radius-lg": "17px",
      "--lt-grid": "36px",
    }),
  },
  "lattice-limestone": {
    name: "Lattice Limestone",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f3f1ec",
      "--lt-bg-raise": "#e9e6df",
      "--lt-panel": "#fcfbf8",
      "--lt-slate": "#716f6a",
      "--lt-text": "#242421",
      "--lt-text-soft": "#4d4c47",
      "--lt-muted": "#75736d",
      "--lt-faint": "#9b9890",
      "--lt-accent": "#315bb5",
      "--lt-accent-bright": "#24458e",
      "--lt-accent-deep": "#19336f",
      "--lt-danger": "#b52f36",
      "--lt-shadow": "#121210",
      "--lt-on-accent": "#f7f9ff",
      "--lt-radius": "6px",
      "--lt-radius-sm": "4px",
      "--lt-radius-lg": "10px",
      "--lt-grid": "30px",
    }),
  },
  cupertino: {
    name: "Cupertino",
    appearance: "light",
    vars: variantVars({
      "--lt-bg": "#f5f5f7",
      "--lt-bg-raise": "#ebebf0",
      "--lt-panel": "#ffffff",
      "--lt-slate": "#6e6e73",
      "--lt-text": "#1d1d1f",
      "--lt-text-soft": "#48484a",
      "--lt-muted": "#86868b",
      "--lt-faint": "#aeaeb2",
      "--lt-accent": "#0071e3",
      "--lt-accent-bright": "#0058b0",
      "--lt-accent-deep": "#003e85",
      "--lt-danger": "#d70015",
      "--lt-shadow": "#1d1d1f",
      "--lt-on-accent": "#ffffff",
      "--lt-font-display":
        '-apple-system, "SF Pro Display", "Helvetica Neue", system-ui, sans-serif',
      "--lt-font-ui": '-apple-system, "SF Pro Text", "Helvetica Neue", system-ui, sans-serif',
      "--lt-font-mono": '"SF Mono", ui-monospace, Menlo, "JetBrains Mono", monospace',
      "--lt-radius": "10px",
      "--lt-radius-sm": "7px",
      "--lt-radius-lg": "16px",
    }),
  },
  "lattice-oled": {
    name: "Lattice OLED",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#000000",
      "--lt-bg-raise": "#050507",
      "--lt-panel": "#0a0a0c",
      "--lt-slate": "#9aa3b2",
      "--lt-text": "#f2f4f8",
      "--lt-text-soft": "#c2c8d2",
      "--lt-muted": "#878e9b",
      "--lt-faint": "#565c66",
      "--lt-accent": "#2ee6a8",
      "--lt-accent-bright": "#8dffd9",
      "--lt-accent-deep": "#0fae7c",
      "--lt-danger": "#ff8095",
      "--lt-on-accent": "#001a10",
    }),
  },
  "catppuccin-mocha": {
    name: "Catppuccin Mocha",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#181825",
      "--lt-bg-raise": "#1e1e2e",
      "--lt-panel": "#313244",
      "--lt-slate": "#9399b2",
      "--lt-text": "#cdd6f4",
      "--lt-text-soft": "#bac2de",
      "--lt-muted": "#a6adc8",
      "--lt-faint": "#7f849c",
      "--lt-accent": "#cba6f7",
      "--lt-accent-bright": "#f5c2e7",
      "--lt-accent-deep": "#a06fe0",
      "--lt-danger": "#f38ba8",
      "--lt-shadow": "#11111b",
      "--lt-on-accent": "#1e1e2e",
      "--lt-term-black": "#45475a",
      "--lt-term-red": "#f38ba8",
      "--lt-term-green": "#a6e3a1",
      "--lt-term-yellow": "#f9e2af",
      "--lt-term-blue": "#89b4fa",
      "--lt-term-magenta": "#f5c2e7",
      "--lt-term-cyan": "#94e2d5",
      "--lt-term-white": "#bac2de",
      "--lt-term-bright-black": "#585b70",
      "--lt-term-bright-red": "#f38ba8",
      "--lt-term-bright-green": "#a6e3a1",
      "--lt-term-bright-yellow": "#f9e2af",
      "--lt-term-bright-blue": "#89b4fa",
      "--lt-term-bright-magenta": "#f5c2e7",
      "--lt-term-bright-cyan": "#94e2d5",
      "--lt-term-bright-white": "#a6adc8",
      "--lt-term-cursor": "#f5e0dc",
      "--lt-term-cursor-text": "#1e1e2e",
      "--lt-term-selection": "#585b7066",
    }),
  },
  nord: {
    name: "Nord",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#2e3440",
      "--lt-bg-raise": "#3b4252",
      "--lt-panel": "#434c5e",
      "--lt-slate": "#81a1c1",
      "--lt-text": "#eceff4",
      "--lt-text-soft": "#d8dee9",
      "--lt-muted": "#a6b0c3",
      "--lt-faint": "#7b88a1",
      "--lt-accent": "#88c0d0",
      "--lt-accent-bright": "#b8e0ea",
      "--lt-accent-deep": "#5e81ac",
      "--lt-danger": "#bf616a",
      "--lt-shadow": "#242933",
      "--lt-on-accent": "#2e3440",
      "--lt-term-black": "#3b4252",
      "--lt-term-red": "#bf616a",
      "--lt-term-green": "#a3be8c",
      "--lt-term-yellow": "#ebcb8b",
      "--lt-term-blue": "#81a1c1",
      "--lt-term-magenta": "#b48ead",
      "--lt-term-cyan": "#88c0d0",
      "--lt-term-white": "#e5e9f0",
      "--lt-term-bright-black": "#4c566a",
      "--lt-term-bright-red": "#bf616a",
      "--lt-term-bright-green": "#a3be8c",
      "--lt-term-bright-yellow": "#ebcb8b",
      "--lt-term-bright-blue": "#81a1c1",
      "--lt-term-bright-magenta": "#b48ead",
      "--lt-term-bright-cyan": "#8fbcbb",
      "--lt-term-bright-white": "#eceff4",
      "--lt-term-cursor": "#d8dee9",
      "--lt-term-cursor-text": "#2e3440",
      "--lt-term-selection": "#434c5e",
    }),
  },
  "github-dark": {
    name: "GitHub Dark",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#0d1117",
      "--lt-bg-raise": "#161b22",
      "--lt-panel": "#21262d",
      "--lt-slate": "#8b949e",
      "--lt-text": "#e6edf3",
      "--lt-text-soft": "#c9d1d9",
      "--lt-muted": "#848d97",
      "--lt-faint": "#6e7681",
      "--lt-accent": "#58a6ff",
      "--lt-accent-bright": "#79c0ff",
      "--lt-accent-deep": "#1f6feb",
      "--lt-danger": "#f85149",
      "--lt-shadow": "#010409",
      "--lt-on-accent": "#05192d",
      "--lt-radius": "6px",
      "--lt-radius-sm": "4px",
      "--lt-radius-lg": "12px",
      "--lt-term-black": "#484f58",
      "--lt-term-red": "#ff7b72",
      "--lt-term-green": "#3fb950",
      "--lt-term-yellow": "#d29922",
      "--lt-term-blue": "#58a6ff",
      "--lt-term-magenta": "#bc8cff",
      "--lt-term-cyan": "#39c5cf",
      "--lt-term-white": "#b1bac4",
      "--lt-term-bright-black": "#6e7681",
      "--lt-term-bright-red": "#ffa198",
      "--lt-term-bright-green": "#56d364",
      "--lt-term-bright-yellow": "#e3b341",
      "--lt-term-bright-blue": "#79c0ff",
      "--lt-term-bright-magenta": "#d2a8ff",
      "--lt-term-bright-cyan": "#56d4dd",
      "--lt-term-bright-white": "#ffffff",
      "--lt-term-cursor": "#58a6ff",
      "--lt-term-cursor-text": "#0d1117",
      "--lt-term-selection": "#388bfd66",
    }),
  },
  dracula: {
    name: "Dracula",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#282a36",
      "--lt-bg-raise": "#343746",
      "--lt-panel": "#44475a",
      "--lt-slate": "#6272a4",
      "--lt-text": "#f8f8f2",
      "--lt-text-soft": "#d5d7e0",
      "--lt-muted": "#9ea1b9",
      "--lt-faint": "#6b6f8c",
      "--lt-accent": "#bd93f9",
      "--lt-accent-bright": "#d6acff",
      "--lt-accent-deep": "#8b5fd6",
      "--lt-danger": "#ff5555",
      "--lt-shadow": "#191a21",
      "--lt-on-accent": "#21222c",
      "--lt-term-black": "#21222c",
      "--lt-term-red": "#ff5555",
      "--lt-term-green": "#50fa7b",
      "--lt-term-yellow": "#f1fa8c",
      "--lt-term-blue": "#bd93f9",
      "--lt-term-magenta": "#ff79c6",
      "--lt-term-cyan": "#8be9fd",
      "--lt-term-white": "#f8f8f2",
      "--lt-term-bright-black": "#6272a4",
      "--lt-term-bright-red": "#ff6e6e",
      "--lt-term-bright-green": "#69ff94",
      "--lt-term-bright-yellow": "#ffffa5",
      "--lt-term-bright-blue": "#d6acff",
      "--lt-term-bright-magenta": "#ff92df",
      "--lt-term-bright-cyan": "#a4ffff",
      "--lt-term-bright-white": "#ffffff",
      "--lt-term-cursor": "#f8f8f2",
      "--lt-term-cursor-text": "#282a36",
      "--lt-term-selection": "#44475a",
    }),
  },
  "solarized-dark": {
    name: "Solarized Dark",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#002b36",
      "--lt-bg-raise": "#073642",
      "--lt-panel": "#0f4a58",
      "--lt-slate": "#586e75",
      "--lt-text": "#93a1a1",
      "--lt-text-soft": "#839496",
      "--lt-muted": "#657b83",
      "--lt-faint": "#586e75",
      "--lt-accent": "#268bd2",
      "--lt-accent-bright": "#5bb3e8",
      "--lt-accent-deep": "#1a6398",
      "--lt-danger": "#dc322f",
      "--lt-shadow": "#001b21",
      "--lt-on-accent": "#fdf6e3",
      "--lt-term-black": "#073642",
      "--lt-term-red": "#dc322f",
      "--lt-term-green": "#859900",
      "--lt-term-yellow": "#b58900",
      "--lt-term-blue": "#268bd2",
      "--lt-term-magenta": "#d33682",
      "--lt-term-cyan": "#2aa198",
      "--lt-term-white": "#eee8d5",
      "--lt-term-bright-black": "#002b36",
      "--lt-term-bright-red": "#cb4b16",
      "--lt-term-bright-green": "#586e75",
      "--lt-term-bright-yellow": "#657b83",
      "--lt-term-bright-blue": "#839496",
      "--lt-term-bright-magenta": "#6c71c4",
      "--lt-term-bright-cyan": "#93a1a1",
      "--lt-term-bright-white": "#fdf6e3",
      "--lt-term-cursor": "#839496",
      "--lt-term-cursor-text": "#002b36",
      "--lt-term-selection": "#073642",
    }),
  },
  "tokyo-night": {
    name: "Tokyo Night",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#1a1b26",
      "--lt-bg-raise": "#16161e",
      "--lt-panel": "#24283b",
      "--lt-slate": "#565f89",
      "--lt-text": "#c0caf5",
      "--lt-text-soft": "#a9b1d6",
      "--lt-muted": "#787c99",
      "--lt-faint": "#565f89",
      "--lt-accent": "#7aa2f7",
      "--lt-accent-bright": "#7dcfff",
      "--lt-accent-deep": "#3d59a1",
      "--lt-danger": "#f7768e",
      "--lt-shadow": "#0f0f14",
      "--lt-on-accent": "#10131c",
      "--lt-term-black": "#15161e",
      "--lt-term-red": "#f7768e",
      "--lt-term-green": "#9ece6a",
      "--lt-term-yellow": "#e0af68",
      "--lt-term-blue": "#7aa2f7",
      "--lt-term-magenta": "#bb9af7",
      "--lt-term-cyan": "#7dcfff",
      "--lt-term-white": "#a9b1d6",
      "--lt-term-bright-black": "#414868",
      "--lt-term-bright-red": "#f7768e",
      "--lt-term-bright-green": "#9ece6a",
      "--lt-term-bright-yellow": "#e0af68",
      "--lt-term-bright-blue": "#7aa2f7",
      "--lt-term-bright-magenta": "#bb9af7",
      "--lt-term-bright-cyan": "#7dcfff",
      "--lt-term-bright-white": "#c0caf5",
      "--lt-term-cursor": "#c0caf5",
      "--lt-term-cursor-text": "#1a1b26",
      "--lt-term-selection": "#33467c",
    }),
  },
  "gruvbox-dark": {
    name: "Gruvbox Dark",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#282828",
      "--lt-bg-raise": "#32302f",
      "--lt-panel": "#3c3836",
      "--lt-slate": "#a89984",
      "--lt-text": "#ebdbb2",
      "--lt-text-soft": "#d5c4a1",
      "--lt-muted": "#a89984",
      "--lt-faint": "#928374",
      "--lt-accent": "#fe8019",
      "--lt-accent-bright": "#fabd2f",
      "--lt-accent-deep": "#d65d0e",
      "--lt-danger": "#fb4934",
      "--lt-shadow": "#1d2021",
      "--lt-on-accent": "#241600",
      "--lt-radius": "8px",
      "--lt-radius-sm": "5px",
      "--lt-radius-lg": "13px",
      "--lt-term-black": "#282828",
      "--lt-term-red": "#cc241d",
      "--lt-term-green": "#98971a",
      "--lt-term-yellow": "#d79921",
      "--lt-term-blue": "#458588",
      "--lt-term-magenta": "#b16286",
      "--lt-term-cyan": "#689d6a",
      "--lt-term-white": "#a89984",
      "--lt-term-bright-black": "#928374",
      "--lt-term-bright-red": "#fb4934",
      "--lt-term-bright-green": "#b8bb26",
      "--lt-term-bright-yellow": "#fabd2f",
      "--lt-term-bright-blue": "#83a598",
      "--lt-term-bright-magenta": "#d3869b",
      "--lt-term-bright-cyan": "#8ec07c",
      "--lt-term-bright-white": "#ebdbb2",
      "--lt-term-cursor": "#ebdbb2",
      "--lt-term-cursor-text": "#282828",
      "--lt-term-selection": "#504945",
    }),
  },
  "one-dark": {
    name: "One Dark",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#282c34",
      "--lt-bg-raise": "#21252b",
      "--lt-panel": "#2f343f",
      "--lt-slate": "#7f848e",
      "--lt-text": "#abb2bf",
      "--lt-text-soft": "#9da5b4",
      "--lt-muted": "#7f848e",
      "--lt-faint": "#5c6370",
      "--lt-accent": "#61afef",
      "--lt-accent-bright": "#8bc7f5",
      "--lt-accent-deep": "#3b86c4",
      "--lt-danger": "#e06c75",
      "--lt-shadow": "#17191e",
      "--lt-on-accent": "#10202d",
      "--lt-radius": "8px",
      "--lt-radius-sm": "5px",
      "--lt-radius-lg": "13px",
      "--lt-term-black": "#1e2127",
      "--lt-term-red": "#e06c75",
      "--lt-term-green": "#98c379",
      "--lt-term-yellow": "#d19a66",
      "--lt-term-blue": "#61afef",
      "--lt-term-magenta": "#c678dd",
      "--lt-term-cyan": "#56b6c2",
      "--lt-term-white": "#abb2bf",
      "--lt-term-bright-black": "#5c6370",
      "--lt-term-bright-red": "#e06c75",
      "--lt-term-bright-green": "#98c379",
      "--lt-term-bright-yellow": "#d19a66",
      "--lt-term-bright-blue": "#61afef",
      "--lt-term-bright-magenta": "#c678dd",
      "--lt-term-bright-cyan": "#56b6c2",
      "--lt-term-bright-white": "#ffffff",
      "--lt-term-cursor": "#abb2bf",
      "--lt-term-cursor-text": "#282c34",
      "--lt-term-selection": "#3e4451",
    }),
  },
  "rose-pine-moon": {
    name: "Rosé Pine Moon",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#232136",
      "--lt-bg-raise": "#2a273f",
      "--lt-panel": "#393552",
      "--lt-slate": "#908caa",
      "--lt-text": "#e0def4",
      "--lt-text-soft": "#908caa",
      "--lt-muted": "#6e6a86",
      "--lt-faint": "#6e6a86",
      "--lt-accent": "#c4a7e7",
      "--lt-accent-bright": "#dbc6f4",
      "--lt-accent-deep": "#907aa9",
      "--lt-danger": "#eb6f92",
      "--lt-shadow": "#191724",
      "--lt-on-accent": "#211b2d",
      "--lt-radius": "10px",
      "--lt-radius-sm": "7px",
      "--lt-radius-lg": "15px",
      "--lt-term-black": "#393552",
      "--lt-term-red": "#eb6f92",
      "--lt-term-green": "#3e8fb0",
      "--lt-term-yellow": "#f6c177",
      "--lt-term-blue": "#9ccfd8",
      "--lt-term-magenta": "#c4a7e7",
      "--lt-term-cyan": "#ea9a97",
      "--lt-term-white": "#e0def4",
      "--lt-term-bright-black": "#6e6a86",
      "--lt-term-bright-red": "#eb6f92",
      "--lt-term-bright-green": "#3e8fb0",
      "--lt-term-bright-yellow": "#f6c177",
      "--lt-term-bright-blue": "#9ccfd8",
      "--lt-term-bright-magenta": "#c4a7e7",
      "--lt-term-bright-cyan": "#ea9a97",
      "--lt-term-bright-white": "#e0def4",
      "--lt-term-cursor": "#e0def4",
      "--lt-term-cursor-text": "#232136",
      "--lt-term-selection": "#44415a",
    }),
  },
  "kanagawa-wave": {
    name: "Kanagawa Wave",
    appearance: "dark",
    vars: variantVars({
      "--lt-bg": "#1f1f28",
      "--lt-bg-raise": "#16161d",
      "--lt-panel": "#2a2a37",
      "--lt-slate": "#9a957d",
      "--lt-text": "#dcd7ba",
      "--lt-text-soft": "#c8c093",
      "--lt-muted": "#9a957d",
      "--lt-faint": "#727169",
      "--lt-accent": "#7e9cd8",
      "--lt-accent-bright": "#7fb4ca",
      "--lt-accent-deep": "#2d4f67",
      "--lt-danger": "#c34043",
      "--lt-shadow": "#090618",
      "--lt-on-accent": "#101522",
      "--lt-term-black": "#090618",
      "--lt-term-red": "#c34043",
      "--lt-term-green": "#76946a",
      "--lt-term-yellow": "#c0a36e",
      "--lt-term-blue": "#7e9cd8",
      "--lt-term-magenta": "#957fb8",
      "--lt-term-cyan": "#6a9589",
      "--lt-term-white": "#c8c093",
      "--lt-term-bright-black": "#727169",
      "--lt-term-bright-red": "#e82424",
      "--lt-term-bright-green": "#98bb6c",
      "--lt-term-bright-yellow": "#e6c384",
      "--lt-term-bright-blue": "#7fb4ca",
      "--lt-term-bright-magenta": "#938aa9",
      "--lt-term-bright-cyan": "#7aa89f",
      "--lt-term-bright-white": "#dcd7ba",
      "--lt-term-cursor": "#c8c093",
      "--lt-term-cursor-text": "#1f1f28",
      "--lt-term-selection": "#2d4f67",
    }),
  },
};

function readPrefs(): DemoPrefs {
  try {
    const raw = localStorage.getItem(DEMO_PREFS_KEY);
    if (!raw) return { ...DEFAULT_PREFS };
    return { ...DEFAULT_PREFS, ...(JSON.parse(raw) as DemoPrefs) };
  } catch {
    return { ...DEFAULT_PREFS };
  }
}

function writePrefs(prefs: DemoPrefs): void {
  localStorage.setItem(DEMO_PREFS_KEY, JSON.stringify(prefs));
}

function builtins() {
  return Object.entries(DEMO_THEMES).map(([id, theme]) => ({
    id,
    name: theme.name,
    appearance: theme.appearance,
    source: "builtin" as const,
    path: `builtin:${id}.theme.yaml`,
  }));
}

function resolveId(prefs: DemoPrefs, system: "dark" | "light"): string {
  if (prefs.mode === "auto") {
    return system === "light" ? prefs.pair.light : prefs.pair.dark;
  }
  return prefs.theme;
}

function buildResolved(
  id: string,
  prefs: DemoPrefs,
): ResolvedThemePayload {
  const theme = DEMO_THEMES[id] ?? DEMO_THEMES["lattice-slate"];
  const vars = { ...theme.vars };
  return {
    id,
    name: theme.name,
    appearance: theme.appearance,
    sourcePath: `builtin:${id}.theme.yaml`,
    vars,
    background: vars["--lt-bg"] ?? "#0a0d13",
    settings: {
      mode: prefs.mode,
      theme: prefs.theme,
      pair: { ...prefs.pair },
    },
    workspaceOverride: {},
    diagnostics: [],
  };
}

export function demoCatalog(
  system: "dark" | "light" = detectSystemAppearance(),
  _workspaceRoot?: string | null,
): ThemeCatalogPayload {
  const prefs = readPrefs();
  const id = resolveId(prefs, system);
  return {
    themes: builtins(),
    diagnostics: [],
    resolved: buildResolved(id, prefs),
  };
}

export function demoSetTheme(
  themeId: string,
  system: "dark" | "light",
): ThemeCatalogPayload {
  const prefs = { ...readPrefs(), mode: "fixed" as const, theme: themeId };
  writePrefs(prefs);
  return demoCatalog(system);
}

export function demoSetAppearanceMode(
  mode: "fixed" | "auto",
  system: "dark" | "light",
): ThemeCatalogPayload {
  const prefs = { ...readPrefs(), mode };
  writePrefs(prefs);
  return demoCatalog(system);
}
