// GENERATED by scripts/compile-templates.mjs — do not edit.
pub(crate) static GENERATED_TEMPLATES: &[GeneratedTemplate] = &[
    GeneratedTemplate {
        id: "personal",
        order: 10,
        name: "Personal",
        category: "Everyday",
        description: "Capture ideas, run projects, manage ongoing areas, and keep a durable library.",
        visibility: "gallery",
        recommended: true,
        recommended_title: "Personal",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: Some("Drop raw captures here — triage them into Projects or Library."), default_kind: None, icon: None },
            SeedDirectory { path: "Projects", purpose: Some("Time-bound outcomes with a clear finish line."), default_kind: None, icon: None },
            SeedDirectory { path: "Areas", purpose: Some("Ongoing responsibilities to maintain over time."), default_kind: None, icon: None },
            SeedDirectory { path: "Library", purpose: Some("Reference material, book notes, and durable knowledge."), default_kind: None, icon: None },
            SeedDirectory { path: "Journal", purpose: Some("Daily notes and periodic reflections."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Reusable note patterns with {{title}} and {{date}} placeholders."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Completed projects and inactive material."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Projects/Example Project.md", "Journal/{{date}}.md", "Templates/Daily.md", "Inbox/", "Projects/", "Journal/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Inbox",
        daily_note_directory: Some("Journal"),
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Home.md")) },
            SeedFile { path: "Welcome.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Welcome.md")) },
            SeedFile { path: "Projects/Example Project.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Projects/Example Project.md")) },
            SeedFile { path: "Journal/{{date}}.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Journal/{{date}}.md")) },
            SeedFile { path: "Templates/Meeting Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Templates/Meeting Note.md")) },
            SeedFile { path: "Templates/Book Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Templates/Book Note.md")) },
            SeedFile { path: "Templates/Daily.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Templates/Daily.md")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "Tasks.data",
            title: "Tasks",
            table: "tasks",
            columns: &[
                SeedDataColumn { name: "task", field_type: "text", relation_table: None },
                SeedDataColumn { name: "status", field_type: "text", relation_table: None },
                SeedDataColumn { name: "due", field_type: "date", relation_table: None }
            ],
            rows_json: &[
                "{\"task\":\"Review inbox\",\"status\":\"todo\",\"due\":null}",
                "{\"task\":\"Plan the week\",\"status\":\"todo\",\"due\":\"2026-07-21\"}"
            ],
            extra_tables: &[],
            views: &[],
            forms: &[],
        }
        ],
    },
    GeneratedTemplate {
        id: "project",
        order: 20,
        name: "Project",
        category: "Work",
        description: "Plan and deliver one outcome with decisions, research, working files, data, and outputs together.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Project",
        directories: &[
            SeedDirectory { path: "Decisions", purpose: Some("Lightweight ADRs and decision records."), default_kind: None, icon: None },
            SeedDirectory { path: "Meetings", purpose: Some("Agendas, notes, and follow-ups from syncs."), default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: Some("Background reading and exploratory notes."), default_kind: None, icon: None },
            SeedDirectory { path: "Working", purpose: Some("Active drafts and in-progress material."), default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: Some("Tables, datasets, and structured inputs."), default_kind: None, icon: None },
            SeedDirectory { path: "Outputs", purpose: Some("Deliverables ready to share."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Reusable patterns for decisions and meetings."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Superseded or completed material."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Brief.md", "Plan.md", "Milestones.canvas", "Decisions/0001 Example decision.md", "Decisions/", "Meetings/", "Working/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Working",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Home.md")) },
            SeedFile { path: "Brief.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Brief.md")) },
            SeedFile { path: "Plan.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Plan.md")) },
            SeedFile { path: "Milestones.canvas", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Milestones.canvas")) },
            SeedFile { path: "Decisions/0001 Example decision.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Decisions/0001 Example decision.md")) },
            SeedFile { path: "Templates/Decision.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Templates/Decision.md")) }
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "writing",
        order: 25,
        name: "Writing",
        category: "Work",
        description: "Draft a manuscript with research, outlines, a style guide, and a submissions tracker beside the prose.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Writing",
        directories: &[
            SeedDirectory { path: "Manuscript", purpose: Some("Chapters and long-form drafts, in reading order."), default_kind: None, icon: None },
            SeedDirectory { path: "Outlines", purpose: Some("Story maps, beat sheets, and structural planning."), default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: Some("Background material, references, and fact-checking."), default_kind: None, icon: None },
            SeedDirectory { path: "Notes", purpose: Some("Fragments, ideas, and scenes that have no home yet."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Page templates with {{title}} and {{date}} placeholders."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Cut scenes, abandoned drafts, and past versions."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Manuscript/Chapter 01.md", "Outlines/Story Map.canvas", "Style Guide.md", "Submissions.data", "Templates/Chapter.md", "Notes/", "Research/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Notes",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Home.md")) },
            SeedFile { path: "Style Guide.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Style Guide.md")) },
            SeedFile { path: "Manuscript/Chapter 01.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Manuscript/Chapter 01.md")) },
            SeedFile { path: "Outlines/Story Map.canvas", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Outlines/Story Map.canvas")) },
            SeedFile { path: "Templates/Chapter.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Templates/Chapter.md")) },
            SeedFile { path: "Templates/Character Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Templates/Character Note.md")) },
            SeedFile { path: "Templates/Daily.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/writing/files/Templates/Daily.md")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "Submissions.data",
            title: "Submissions",
            table: "submissions",
            columns: &[
                SeedDataColumn { name: "piece", field_type: "text", relation_table: None },
                SeedDataColumn { name: "venue", field_type: "text", relation_table: None },
                SeedDataColumn { name: "status", field_type: "text", relation_table: None },
                SeedDataColumn { name: "submitted_on", field_type: "date", relation_table: None },
                SeedDataColumn { name: "response", field_type: "long_text", relation_table: None }
            ],
            rows_json: &[
                "{\"piece\":\"Chapter 01 excerpt\",\"venue\":\"Example Quarterly\",\"status\":\"submitted\",\"submitted_on\":\"2026-07-01\",\"response\":null}",
                "{\"piece\":\"Flash piece\",\"venue\":\"Example Review\",\"status\":\"draft\",\"submitted_on\":null,\"response\":\"Polish the opening before sending.\"}"
            ],
            extra_tables: &[],
            views: &[],
            forms: &[],
        }
        ],
    },
    GeneratedTemplate {
        id: "ops",
        order: 27,
        name: "Meetings & Ops",
        category: "Work",
        description: "Run meetings, one-on-ones, weekly reviews, and OKRs from one operational hub.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Ops",
        directories: &[
            SeedDirectory { path: "Meetings", purpose: Some("Dated meeting notes — agendas, decisions, and follow-ups."), default_kind: None, icon: None },
            SeedDirectory { path: "1-1s", purpose: Some("One page per person, appended over time."), default_kind: None, icon: None },
            SeedDirectory { path: "Reviews", purpose: Some("Weekly and quarterly reviews of what actually happened."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Page templates with {{title}} and {{date}} placeholders."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Closed-out meetings and past cycles."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Meetings/{{date}} Kickoff.md", "OKRs.data", "Templates/Meeting Note.md", "Templates/Weekly Review.md", "Meetings/", "1-1s/", "Reviews/"],
        capabilities: &["pages", "sqlite"],
        quick_note_directory: "Meetings",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/ops/files/Home.md")) },
            SeedFile { path: "Meetings/{{date}} Kickoff.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/ops/files/Meetings/{{date}} Kickoff.md")) },
            SeedFile { path: "Templates/Meeting Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/ops/files/Templates/Meeting Note.md")) },
            SeedFile { path: "Templates/One-on-One.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/ops/files/Templates/One-on-One.md")) },
            SeedFile { path: "Templates/Weekly Review.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/ops/files/Templates/Weekly Review.md")) },
            SeedFile { path: "Templates/Daily.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/ops/files/Templates/Daily.md")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "OKRs.data",
            title: "OKRs",
            table: "okrs",
            columns: &[
                SeedDataColumn { name: "objective", field_type: "text", relation_table: None },
                SeedDataColumn { name: "key_result", field_type: "text", relation_table: None },
                SeedDataColumn { name: "owner", field_type: "text", relation_table: None },
                SeedDataColumn { name: "status", field_type: "text", relation_table: None },
                SeedDataColumn { name: "confidence", field_type: "decimal", relation_table: None }
            ],
            rows_json: &[
                "{\"objective\":\"Ship the spring release\",\"key_result\":\"All launch blockers closed by the freeze date\",\"owner\":\"you\",\"status\":\"on-track\",\"confidence\":0.8}",
                "{\"objective\":\"Ship the spring release\",\"key_result\":\"Two demo rounds with written findings\",\"owner\":\"you\",\"status\":\"at-risk\",\"confidence\":0.5}",
                "{\"objective\":\"Grow the team sustainably\",\"key_result\":\"Every report has a current growth plan\",\"owner\":\"you\",\"status\":\"on-track\",\"confidence\":0.7}"
            ],
            extra_tables: &[],
            views: &[],
            forms: &[],
        }
        ],
    },
    GeneratedTemplate {
        id: "research",
        order: 30,
        name: "Research",
        category: "Knowledge & Research",
        description: "Move from questions and sources through notes, experiments, analysis, and published outputs.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Research",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: Some("Unprocessed captures awaiting triage."), default_kind: None, icon: None },
            SeedDirectory { path: "Sources", purpose: Some("Literature notes with citation metadata."), default_kind: None, icon: None },
            SeedDirectory { path: "Notes", purpose: Some("Developing ideas and synthesis."), default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: Some("Datasets supporting analysis."), default_kind: None, icon: None },
            SeedDirectory { path: "Experiments", purpose: Some("Reproducible runs and protocols."), default_kind: None, icon: None },
            SeedDirectory { path: "Outputs", purpose: Some("Published findings and write-ups."), default_kind: None, icon: None },
            SeedDirectory { path: "Bibliography", purpose: Some("Formal reference list and exports."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Completed or superseded research."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Page templates with {{title}} and {{date}} placeholders."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Questions.md", "Sources/Example Paper.md", "Sources/", "Notes/", "Experiments/", "Outputs/", "Templates/Literature Note.md"],
        capabilities: &["pages", "canvas", "sqlite", "citations"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Home.md")) },
            SeedFile { path: "Questions.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Questions.md")) },
            SeedFile { path: "Sources/Example Paper.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Sources/Example Paper.md")) },
            SeedFile { path: "Templates/Literature Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Templates/Literature Note.md")) },
            SeedFile { path: "Templates/Experiment.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Templates/Experiment.md")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "Experiments/experiments-log.data",
            title: "Experiments log",
            table: "experiments",
            columns: &[
                SeedDataColumn { name: "name", field_type: "text", relation_table: None },
                SeedDataColumn { name: "status", field_type: "text", relation_table: None },
                SeedDataColumn { name: "run_date", field_type: "date", relation_table: None },
                SeedDataColumn { name: "notes", field_type: "long_text", relation_table: None }
            ],
            rows_json: &[
                "{\"name\":\"Baseline replication\",\"status\":\"planned\",\"run_date\":null,\"notes\":\"Replicate methods from Example Paper.\"}",
                "{\"name\":\"Pilot run\",\"status\":\"complete\",\"run_date\":\"2026-07-10\",\"notes\":\"Smoke test of data pipeline.\"}"
            ],
            extra_tables: &[],
            views: &[],
            forms: &[],
        }
        ],
    },
    GeneratedTemplate {
        id: "second-brain",
        order: 35,
        name: "Second Brain",
        category: "Knowledge & Research",
        description: "Capture fleeting ideas, grow atomic notes, and navigate your knowledge with maps of content and agent-ready context.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Second Brain",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: Some("Fleeting captures and unsorted inputs — triage into Notes or Sources."), default_kind: None, icon: None },
            SeedDirectory { path: "Notes", purpose: Some("Atomic, densely linked notes that accrue meaning over time."), default_kind: None, icon: None },
            SeedDirectory { path: "MOCs", purpose: Some("Maps of content that orient you across topics without rigid folders."), default_kind: None, icon: None },
            SeedDirectory { path: "Sources", purpose: Some("Books, papers, articles, and media you want to cite or distill."), default_kind: None, icon: None },
            SeedDirectory { path: "Context", purpose: Some("Workspace context for humans and agents — scope, tone, and conventions."), default_kind: None, icon: None },
            SeedDirectory { path: "Prompts", purpose: Some("Reusable prompt patterns for synthesis, review, and extraction."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Page templates with {{title}} and {{date}} placeholders."), default_kind: None, icon: None }
        ],
        preview: &["MOCs/Knowledge Base.md", "Notes/Capture Workflow.md", "Notes/Evergreen Notes.md", "Notes/Linking Philosophy.md", "Inbox/", "Sources/", "Context/AGENTS.md", "Templates/Daily.md", "Prompts/"],
        capabilities: &["pages", "citations"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: None,
        open_on_create: Some("MOCs/Knowledge Base.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Home.md")) },
            SeedFile { path: "MOCs/Knowledge Base.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/MOCs/Knowledge Base.md")) },
            SeedFile { path: "Notes/Capture Workflow.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Notes/Capture Workflow.md")) },
            SeedFile { path: "Notes/Evergreen Notes.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Notes/Evergreen Notes.md")) },
            SeedFile { path: "Notes/Linking Philosophy.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Notes/Linking Philosophy.md")) },
            SeedFile { path: "Notes/Progressive Summarization.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Notes/Progressive Summarization.md")) },
            SeedFile { path: "Notes/Spaced Repetition.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Notes/Spaced Repetition.md")) },
            SeedFile { path: "Notes/Zettelkasten Primer.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Notes/Zettelkasten Primer.md")) },
            SeedFile { path: "Context/AGENTS.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Context/AGENTS.md")) },
            SeedFile { path: "Templates/Daily.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Templates/Daily.md")) },
            SeedFile { path: "Prompts/Synthesize Connections.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Prompts/Synthesize Connections.md")) },
            SeedFile { path: "Prompts/Weekly Review.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Prompts/Weekly Review.md")) },
            SeedFile { path: "Prompts/Extract Key Ideas.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/second-brain/files/Prompts/Extract Key Ideas.md")) }
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "data-lab",
        order: 40,
        name: "Data Lab",
        category: "Data & Advanced",
        description: "Organize data sources, queries, notebooks, dashboards, reports, and reusable analysis.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Data Lab",
        directories: &[
            SeedDirectory { path: "Connections", purpose: Some("Database, API, and file connection definitions."), default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: Some("Canonical datasets and curated tables."), default_kind: None, icon: None },
            SeedDirectory { path: "Queries", purpose: Some("Reusable SQL and saved query definitions."), default_kind: None, icon: None },
            SeedDirectory { path: "Notebooks", purpose: Some("Reproducible analysis notebooks."), default_kind: None, icon: None },
            SeedDirectory { path: "Dashboards", purpose: Some("Interactive summaries and charts."), default_kind: None, icon: None },
            SeedDirectory { path: "Reports", purpose: Some("Narrative findings and published analysis."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Deprecated datasets and old reports."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Data/contacts.csv", "Queries/example.sql", "Notebooks/example.ipynb", "Connections/", "Data/", "Queries/", "Notebooks/"],
        capabilities: &["pages", "canvas", "sqlite", "jupyter"],
        quick_note_directory: "Reports",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/data-lab/files/Home.md")) },
            SeedFile { path: "Data/contacts.csv", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/data-lab/files/Data/contacts.csv")) },
            SeedFile { path: "Queries/example.sql", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/data-lab/files/Queries/example.sql")) },
            SeedFile { path: "Notebooks/example.ipynb", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/data-lab/files/Notebooks/example.ipynb")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "Data/metrics.data",
            title: "Metrics",
            table: "metrics",
            columns: &[
                SeedDataColumn { name: "metric", field_type: "text", relation_table: None },
                SeedDataColumn { name: "value", field_type: "decimal", relation_table: None },
                SeedDataColumn { name: "recorded_on", field_type: "date", relation_table: None },
                SeedDataColumn { name: "category", field_type: "text", relation_table: None }
            ],
            rows_json: &[
                "{\"metric\":\"active_users\",\"value\":128,\"recorded_on\":\"2026-07-01\",\"category\":\"Engagement\"}",
                "{\"metric\":\"query_latency_ms\",\"value\":42.5,\"recorded_on\":\"2026-07-01\",\"category\":\"Performance\"}",
                "{\"metric\":\"active_users\",\"value\":142,\"recorded_on\":\"2026-07-08\",\"category\":\"Engagement\"}",
                "{\"metric\":\"query_latency_ms\",\"value\":38.2,\"recorded_on\":\"2026-07-08\",\"category\":\"Performance\"}",
                "{\"metric\":\"error_rate_pct\",\"value\":0.3,\"recorded_on\":\"2026-07-08\",\"category\":\"Reliability\"}"
            ],
            extra_tables: &[],
            views: &[
                SeedDataView {
                name: "Board",
                layout: "board",
                group_by: Some("category"),
                cover_field: None,
                date_field: None,
                columns: &[
                    "metric",
                    "value",
                    "category"
                ],
            },
                SeedDataView {
                name: "Calendar",
                layout: "calendar",
                group_by: None,
                cover_field: None,
                date_field: Some("recorded_on"),
                columns: &[],
            },
                SeedDataView {
                name: "Gallery",
                layout: "gallery",
                group_by: None,
                cover_field: Some("metric"),
                date_field: None,
                columns: &[],
            },
                SeedDataView {
                name: "Form",
                layout: "form",
                group_by: None,
                cover_field: None,
                date_field: None,
                columns: &[],
            }
            ],
            forms: &[],
        }
        ],
    },
    GeneratedTemplate {
        id: "dev-notebook",
        order: 45,
        name: "Dev Notebook",
        category: "Work",
        description: "Track architecture, decisions, snippets, runbooks, debug notes, and issues in one engineering workspace.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Dev Notebook",
        directories: &[
            SeedDirectory { path: "Architecture", purpose: Some("System diagrams, canvases, and structural notes."), default_kind: None, icon: None },
            SeedDirectory { path: "Decisions", purpose: Some("Architecture decision records and technical rationale."), default_kind: None, icon: None },
            SeedDirectory { path: "Snippets", purpose: Some("Reusable TypeScript, Rust, SQL, and shell fragments."), default_kind: Some("file"), icon: None },
            SeedDirectory { path: "Runbooks", purpose: Some("Operational procedures, deploy steps, and incident playbooks."), default_kind: None, icon: None },
            SeedDirectory { path: "Debug Journal", purpose: Some("Timestamped investigation notes, repro steps, and hypotheses."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Page templates with {{title}} and {{date}} placeholders."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Retired notes, resolved issues, and superseded decisions."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Architecture/System Overview.canvas", "Architecture/Component Map.md", "Decisions/0001-record-architecture-decisions.md", "Snippets/", "Runbooks/", "Issues.data", "Templates/Debug Session.md"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Debug Journal",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Home.md")) },
            SeedFile { path: "Architecture/System Overview.canvas", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Architecture/System Overview.canvas")) },
            SeedFile { path: "Architecture/Component Map.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Architecture/Component Map.md")) },
            SeedFile { path: "Decisions/0001-record-architecture-decisions.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Decisions/0001-record-architecture-decisions.md")) },
            SeedFile { path: "Snippets/api-handler.ts", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Snippets/api-handler.ts")) },
            SeedFile { path: "Snippets/query.sql", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Snippets/query.sql")) },
            SeedFile { path: "Snippets/lib-helper.rs", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Snippets/lib-helper.rs")) },
            SeedFile { path: "Runbooks/Incident Response.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Runbooks/Incident Response.md")) },
            SeedFile { path: "Templates/Debug Session.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Templates/Debug Session.md")) },
            SeedFile { path: "Templates/Decision.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Templates/Decision.md")) },
            SeedFile { path: "Templates/Daily.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/dev-notebook/files/Templates/Daily.md")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "Issues.data",
            title: "Issues",
            table: "issues",
            columns: &[
                SeedDataColumn { name: "title", field_type: "text", relation_table: None },
                SeedDataColumn { name: "status", field_type: "text", relation_table: None },
                SeedDataColumn { name: "priority", field_type: "text", relation_table: None },
                SeedDataColumn { name: "component", field_type: "text", relation_table: None },
                SeedDataColumn { name: "notes", field_type: "long_text", relation_table: None }
            ],
            rows_json: &[
                "{\"title\":\"Provision workspace from template\",\"status\":\"done\",\"priority\":\"medium\",\"component\":\"tooling\",\"notes\":\"Seed Issues.data and verify wiki links on Home.md.\"}",
                "{\"title\":\"Add health check endpoint\",\"status\":\"open\",\"priority\":\"high\",\"component\":\"api\",\"notes\":\"See Snippets/api-handler.ts for the handler stub.\"}",
                "{\"title\":\"Document deploy rollback\",\"status\":\"open\",\"priority\":\"low\",\"component\":\"ops\",\"notes\":\"Capture steps in Runbooks/ before the next release.\"}"
            ],
            extra_tables: &[],
            views: &[],
            forms: &[],
        }
        ],
    },
    GeneratedTemplate {
        id: "blank",
        order: 50,
        name: "Blank",
        category: "Data & Advanced",
        description: "Start with only lattice.yaml and shape the workspace yourself.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Workspace",
        directories: &[
            
        ],
        preview: &["lattice.yaml"],
        capabilities: &["pages"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: None,
        open_on_create: None,
        files: &[
            
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "demo",
        order: 60,
        name: "First Look",
        category: "Sample",
        description: "Kitchen-sink sample for demos: long pages, CRM, canvas, templates, Mermaid, embeds, and assorted files.",
        visibility: "sample",
        recommended: false,
        recommended_title: "First Look",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: Some("Drop quick captures here — triage into Product or Research."), default_kind: None, icon: None },
            SeedDirectory { path: "Projects", purpose: Some("Active workstreams with a clear outcome."), default_kind: None, icon: None },
            SeedDirectory { path: "Product", purpose: Some("Product narrative, vision, principles, and roadmap pages."), default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: Some("Notes, comparisons, long reads, and diagrams."), default_kind: None, icon: None },
            SeedDirectory { path: "Notebooks", purpose: Some("Reproducible analysis notebooks beside CRM and CSV seeds."), default_kind: None, icon: None },
            SeedDirectory { path: "Canvases", purpose: Some("Spatial boards that link into workspace files."), default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: Some("Page templates with {{title}} and {{date}} placeholders."), default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: Some("Tabular seeds and imported tables."), default_kind: None, icon: None },
            SeedDirectory { path: "Resources", purpose: Some("Ordinary files — JSON, YAML, code, SQL, images."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Finished or inactive material."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Research/Long Read.md", "Product/Vision.md", "Product/Principles.md", "CRM.data", "Canvases/Product Strategy.canvas", "Inbox/Sample capture.md", "Templates/Daily Note.md", "Notebooks/CRM exploration.ipynb", "Resources/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Home.md")) },
            SeedFile { path: "Inbox/Sample capture.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Inbox/Sample capture.md")) },
            SeedFile { path: "Product/Vision.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Product/Vision.md")) },
            SeedFile { path: "Product/Principles.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Product/Principles.md")) },
            SeedFile { path: "Product/Roadmap.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Product/Roadmap.md")) },
            SeedFile { path: "Product/Release Notes.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Product/Release Notes.md")) },
            SeedFile { path: "Research/Long Read.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Long Read.md")) },
            SeedFile { path: "Research/Competitor Analysis.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Competitor Analysis.md")) },
            SeedFile { path: "Research/Architecture.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Architecture.md")) },
            SeedFile { path: "Research/Market Notes.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Market Notes.md")) },
            SeedFile { path: "Research/Interview Synthesis.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Interview Synthesis.md")) },
            SeedFile { path: "Templates/Daily Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Templates/Daily Note.md")) },
            SeedFile { path: "Templates/Meeting Note.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Templates/Meeting Note.md")) },
            SeedFile { path: "Notebooks/CRM exploration.ipynb", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Notebooks/CRM exploration.ipynb")) },
            SeedFile { path: "Canvases/Product Strategy.canvas", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Canvases/Product Strategy.canvas")) },
            SeedFile { path: "Data/sample.csv", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Data/sample.csv")) },
            SeedFile { path: "Resources/config.json", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/config.json")) },
            SeedFile { path: "Resources/schema.yaml", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/schema.yaml")) },
            SeedFile { path: "Resources/hooks.json", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/hooks.json")) },
            SeedFile { path: "Resources/notes.txt", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/notes.txt")) },
            SeedFile { path: "Resources/example.ts", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/example.ts")) },
            SeedFile { path: "Resources/types.ts", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/types.ts")) },
            SeedFile { path: "Resources/queries.sql", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/queries.sql")) },
            SeedFile { path: "Resources/mark.svg", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/mark.svg")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "CRM.data",
            title: "CRM",
            table: "contacts",
            columns: &[
                SeedDataColumn { name: "name", field_type: "text", relation_table: None },
                SeedDataColumn { name: "email", field_type: "text", relation_table: None },
                SeedDataColumn { name: "company", field_type: "relation", relation_table: Some("companies") },
                SeedDataColumn { name: "due_date", field_type: "date", relation_table: None },
                SeedDataColumn { name: "status", field_type: "text", relation_table: None },
                SeedDataColumn { name: "notes", field_type: "long_text", relation_table: None },
                SeedDataColumn { name: "reports_to", field_type: "relation", relation_table: Some("contacts") }
            ],
            rows_json: &[
                "{\"name\":\"Ada Lovelace\",\"email\":\"ada@analytical.io\",\"company\":[\"Analytical Engines\"],\"due_date\":\"2026-08-15\",\"status\":\"Active\",\"notes\":\"Champion for typed tables beside narrative docs.\"}",
                "{\"name\":\"Grace Hopper\",\"email\":\"grace@navy.mil\",\"company\":[\"US Navy\"],\"due_date\":\"2026-07-25\",\"status\":\"Active\",\"notes\":\"Asked for honest SQL export from CRM views.\",\"reports_to\":[\"Ada Lovelace\"]}",
                "{\"name\":\"Alan Turing\",\"email\":\"alan@bletchley.uk\",\"company\":[\"Bletchley Park\"],\"due_date\":\"2026-09-01\",\"status\":\"Nurture\",\"notes\":\"Interested after notebook preview ships.\"}",
                "{\"name\":\"Katherine Johnson\",\"email\":\"katherine@nasa.gov\",\"company\":[\"NASA\"],\"due_date\":\"2026-08-02\",\"status\":\"Active\",\"notes\":\"Needs calendar layout on due dates for standup.\",\"reports_to\":[\"Dorothy Vaughan\"]}",
                "{\"name\":\"Dorothy Vaughan\",\"email\":\"dorothy@nasa.gov\",\"company\":[\"NASA\"],\"due_date\":null,\"status\":\"Partner\",\"notes\":\"Coordinating team rollout; gallery view by company.\"}",
                "{\"name\":\"Mary Jackson\",\"email\":\"mary@nasa.gov\",\"company\":[\"NASA\"],\"due_date\":\"2026-07-30\",\"status\":\"Active\",\"notes\":\"Wants board grouped by status for sprint review.\",\"reports_to\":[\"Katherine Johnson\"]}",
                "{\"name\":\"Tim Berners-Lee\",\"email\":\"tim@w3.org\",\"company\":[\"W3C\"],\"due_date\":\"2026-10-12\",\"status\":\"Lead\",\"notes\":\"Linked data angle — follow up on wiki link semantics.\"}",
                "{\"name\":\"Brendan Eich\",\"email\":\"brendan@mozilla.org\",\"company\":[\"Mozilla\"],\"due_date\":\"2026-08-20\",\"status\":\"Nurture\",\"notes\":\"Curious about Tauri shell performance budgets.\"}",
                "{\"name\":\"Margaret Hamilton\",\"email\":\"margaret@mit.edu\",\"company\":[\"MIT Instrumentation Lab\"],\"due_date\":\"2026-07-22\",\"status\":\"Active\",\"notes\":\"Long-page scroll tests map to her reliability bar.\"}",
                "{\"name\":\"Donald Knuth\",\"email\":\"knuth@stanford.edu\",\"company\":[\"Stanford\"],\"due_date\":null,\"status\":\"Lead\",\"notes\":\"Literate programming — pages + code in Resources/.\"}",
                "{\"name\":\"Linus Torvalds\",\"email\":\"linus@linux.foundation\",\"company\":[\"Linux Foundation\"],\"due_date\":\"2026-11-05\",\"status\":\"Nurture\",\"notes\":\"Git-friendly workspace layout is the hook.\"}",
                "{\"name\":\"Guido van Rossum\",\"email\":\"guido@python.org\",\"company\":[\"Python Software Foundation\"],\"due_date\":\"2026-08-08\",\"status\":\"Active\",\"notes\":\"Notebook story — track under Notebooks/ when ready.\"}",
                "{\"name\":\"Radia Perlman\",\"email\":\"radia@ieee.org\",\"company\":[\"IEEE\"],\"due_date\":\"2026-09-18\",\"status\":\"Lead\",\"notes\":\"Spanning-tree metaphor for canvas + outline sync.\"}",
                "{\"name\":\"Shafi Goldwasser\",\"email\":\"shafi@mit.edu\",\"company\":[\"MIT\"],\"due_date\":\"2026-07-28\",\"status\":\"Active\",\"notes\":\"Security review of command preconditions.\",\"reports_to\":[\"Barbara Liskov\"]}",
                "{\"name\":\"Barbara Liskov\",\"email\":\"liskov@mit.edu\",\"company\":[\"MIT\"],\"due_date\":null,\"status\":\"Partner\",\"notes\":\"Substitution principle maps to resource adapters.\"}",
                "{\"name\":\"Frances Allen\",\"email\":\"frances@ibm.com\",\"company\":[\"IBM Research\"],\"due_date\":\"2026-08-30\",\"status\":\"Churned\",\"notes\":\"Paused — re-engage after perf benchmarks published.\"}",
                "{\"name\":\"Edsger Dijkstra\",\"email\":\"edsger@utexas.edu\",\"company\":[\"UT Austin\"],\"due_date\":\"2026-12-01\",\"status\":\"Lead\",\"notes\":\"Structured note templates under Templates/.\"}",
                "{\"name\":\"Grace Brewster\",\"email\":\"grace.b@example.com\",\"company\":[\"Example Corp\"],\"due_date\":\"2026-07-19\",\"status\":\"Lead\",\"notes\":\"Inbound from conference booth — assign owner.\"}",
                "{\"name\":\"Leslie Lamport\",\"email\":\"lamport@microsoft.com\",\"company\":[\"Microsoft Research\"],\"due_date\":\"2026-09-25\",\"status\":\"Nurture\",\"notes\":\"Formal methods audience — link Research/Architecture.\"}",
                "{\"name\":\"Vint Cerf\",\"email\":\"vint@google.com\",\"company\":[\"Google\"],\"due_date\":\"2026-10-01\",\"status\":\"Active\",\"notes\":\"Offline-first narrative resonates; wants demo workspace zip.\"}"
            ],
            extra_tables: &[
                SeedDataExtraTable {
                table: "companies",
                columns: &[
                    SeedDataColumn { name: "name", field_type: "text", relation_table: None }
                ],
                rows_json: &[
                    "{\"name\":\"Analytical Engines\"}",
                "{\"name\":\"US Navy\"}",
                "{\"name\":\"Bletchley Park\"}",
                "{\"name\":\"NASA\"}",
                "{\"name\":\"W3C\"}",
                "{\"name\":\"Mozilla\"}",
                "{\"name\":\"MIT Instrumentation Lab\"}",
                "{\"name\":\"Stanford\"}",
                "{\"name\":\"Linux Foundation\"}",
                "{\"name\":\"Python Software Foundation\"}",
                "{\"name\":\"IEEE\"}",
                "{\"name\":\"MIT\"}",
                "{\"name\":\"IBM Research\"}",
                "{\"name\":\"UT Austin\"}",
                "{\"name\":\"Example Corp\"}",
                "{\"name\":\"Microsoft Research\"}",
                "{\"name\":\"Google\"}"
                ],
            }
            ],
            views: &[
                SeedDataView {
                name: "Board",
                layout: "board",
                group_by: Some("status"),
                cover_field: None,
                date_field: None,
                columns: &[
                    "name",
                    "status"
                ],
            },
                SeedDataView {
                name: "Calendar",
                layout: "calendar",
                group_by: None,
                cover_field: None,
                date_field: Some("due_date"),
                columns: &[],
            },
                SeedDataView {
                name: "Gallery",
                layout: "gallery",
                group_by: None,
                cover_field: Some("company"),
                date_field: None,
                columns: &[],
            },
                SeedDataView {
                name: "Form",
                layout: "form",
                group_by: None,
                cover_field: None,
                date_field: None,
                columns: &[],
            }
            ],
            forms: &[
                SeedDataForm {
                name: "ContactIntake",
                table: "contacts",
                fields: &[
                    "name",
                    "email",
                    "status",
                    "company"
                ],
                title: Some("Contact intake"),
                description: Some("Create a contact from the package form."),
            }
            ],
        }
        ],
    },
    GeneratedTemplate {
        id: "team",
        order: 90,
        name: "Team",
        category: "Work",
        description: "Legacy shared-workspace scaffold retained for CLI compatibility.",
        visibility: "legacy",
        recommended: false,
        recommended_title: "Team",
        directories: &[
            SeedDirectory { path: "Projects", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Docs", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Meetings", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: None, default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Projects/", "Docs/", "Meetings/", "Research/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Meetings",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/team/files/Home.md")) }
        ],
        data_packages: &[
            
        ],
    }
];
