// GENERATED by scripts/compile-templates.mjs — do not edit.
pub(crate) static GENERATED_TEMPLATES: &[GeneratedTemplate] = &[
    GeneratedTemplate {
        id: "personal",
        order: 10,
        name: "Personal",
        category: "Everyday",
        description: "Capture ideas, run projects, manage ongoing areas, and keep a durable library.",
        visibility: "gallery",
        recommended: true,
        recommended_title: "Personal",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: Some("Drop raw captures here — triage them into Projects or Library."), default_kind: None, icon: None },
            SeedDirectory { path: "Projects", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Areas", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Library", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Journal", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Templates", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: None, default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Welcome.md", "Inbox/", "Projects/", "Areas/", "Library/", "Journal/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Inbox",
        daily_note_directory: Some("Journal"),
        attachments_directory: None,
        template_directory: Some("Templates"),
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Home.md")) },
            SeedFile { path: "Welcome.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/personal/files/Welcome.md")) }
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "project",
        order: 20,
        name: "Project",
        category: "Work",
        description: "Plan and deliver one outcome with decisions, research, working files, data, and outputs together.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Project",
        directories: &[
            SeedDirectory { path: "Decisions", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Working", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Outputs", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: None, default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Brief.md", "Plan.md", "Decisions/", "Working/", "Data/", "Outputs/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Working",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Home.md")) },
            SeedFile { path: "Brief.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Brief.md")) },
            SeedFile { path: "Plan.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/project/files/Plan.md")) }
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "research",
        order: 30,
        name: "Research",
        category: "Knowledge & Research",
        description: "Move from questions and sources through notes, experiments, analysis, and published outputs.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Research",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Sources", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Notes", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Experiments", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Outputs", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Bibliography", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: None, default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Questions.md", "Sources/", "Notes/", "Data/", "Experiments/", "Outputs/"],
        capabilities: &["pages", "canvas", "sqlite", "citations"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Home.md")) },
            SeedFile { path: "Questions.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/research/files/Questions.md")) }
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "data-lab",
        order: 40,
        name: "Data Lab",
        category: "Data & Advanced",
        description: "Organize data sources, queries, notebooks, dashboards, reports, and reusable analysis.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Data Lab",
        directories: &[
            SeedDirectory { path: "Sources", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Queries", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Notebooks", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Dashboards", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Reports", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: None, default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Sources/", "Data/", "Queries/", "Notebooks/", "Dashboards/", "Reports/"],
        capabilities: &["pages", "canvas", "sqlite", "jupyter"],
        quick_note_directory: "Reports",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/data-lab/files/Home.md")) }
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "blank",
        order: 50,
        name: "Blank",
        category: "Data & Advanced",
        description: "Start with only lattice.yaml and shape the workspace yourself.",
        visibility: "gallery",
        recommended: false,
        recommended_title: "Workspace",
        directories: &[
            
        ],
        preview: &["lattice.yaml"],
        capabilities: &["pages"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: None,
        open_on_create: None,
        files: &[
            
        ],
        data_packages: &[
            
        ],
    },
    GeneratedTemplate {
        id: "demo",
        order: 60,
        name: "First Look",
        category: "Sample",
        description: "A kitchen-sink sample with pages, canvas, files, CSV, Mermaid, an image, and a CRM data app.",
        visibility: "sample",
        recommended: false,
        recommended_title: "First Look",
        directories: &[
            SeedDirectory { path: "Inbox", purpose: Some("Drop quick captures here — triage into Product or Research."), default_kind: None, icon: None },
            SeedDirectory { path: "Projects", purpose: Some("Active workstreams with a clear outcome."), default_kind: None, icon: None },
            SeedDirectory { path: "Product", purpose: Some("Product narrative, vision, and roadmap pages."), default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: Some("Notes, comparisons, and diagrams."), default_kind: None, icon: None },
            SeedDirectory { path: "Notebooks", purpose: Some("Reserved for notebook resources."), default_kind: None, icon: None },
            SeedDirectory { path: "Canvases", purpose: Some("Spatial boards that link into workspace files."), default_kind: None, icon: None },
            SeedDirectory { path: "Data", purpose: Some("Tabular seeds and imported tables."), default_kind: None, icon: None },
            SeedDirectory { path: "Resources", purpose: Some("Ordinary files — JSON, YAML, code, images."), default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: Some("Finished or inactive material."), default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Product/Vision.md", "Product/Roadmap.md", "Research/Competitor Analysis.md", "Research/Architecture.md", "Canvases/Product Strategy.canvas", "CRM.data", "Data/sample.csv", "Resources/config.json"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Inbox",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Home.md")) },
            SeedFile { path: "Product/Vision.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Product/Vision.md")) },
            SeedFile { path: "Product/Roadmap.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Product/Roadmap.md")) },
            SeedFile { path: "Research/Competitor Analysis.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Competitor Analysis.md")) },
            SeedFile { path: "Research/Architecture.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Research/Architecture.md")) },
            SeedFile { path: "Canvases/Product Strategy.canvas", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Canvases/Product Strategy.canvas")) },
            SeedFile { path: "Data/sample.csv", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Data/sample.csv")) },
            SeedFile { path: "Resources/config.json", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/config.json")) },
            SeedFile { path: "Resources/schema.yaml", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/schema.yaml")) },
            SeedFile { path: "Resources/notes.txt", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/notes.txt")) },
            SeedFile { path: "Resources/example.ts", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/example.ts")) },
            SeedFile { path: "Resources/mark.svg", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/demo/files/Resources/mark.svg")) }
        ],
        data_packages: &[
            SeedDataPackage {
            path: "CRM.data",
            title: "CRM",
            table: "contacts",
            columns: &[
                SeedDataColumn { name: "name", field_type: "text" },
                SeedDataColumn { name: "status", field_type: "text" }
            ],
            rows_json: &[
                "{\"name\":\"Ada Lovelace\",\"status\":\"Active\"}",
                "{\"name\":\"Grace Hopper\",\"status\":\"Active\"}"
            ],
        }
        ],
    },
    GeneratedTemplate {
        id: "team",
        order: 90,
        name: "Team",
        category: "Work",
        description: "Legacy shared-workspace scaffold retained for CLI compatibility.",
        visibility: "legacy",
        recommended: false,
        recommended_title: "Team",
        directories: &[
            SeedDirectory { path: "Projects", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Docs", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Meetings", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Research", purpose: None, default_kind: None, icon: None },
            SeedDirectory { path: "Archive", purpose: None, default_kind: None, icon: None }
        ],
        preview: &["Home.md", "Projects/", "Docs/", "Meetings/", "Research/"],
        capabilities: &["pages", "canvas", "sqlite"],
        quick_note_directory: "Meetings",
        daily_note_directory: None,
        attachments_directory: None,
        template_directory: None,
        archive_directory: Some("Archive"),
        open_on_create: Some("Home.md"),
        files: &[
            SeedFile { path: "Home.md", bytes: include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/../../templates/workspaces/team/files/Home.md")) }
        ],
        data_packages: &[
            
        ],
    }
];
