// GENERATED by scripts/compile-templates.mjs — do not edit.
import type { WorkspaceSnapshot } from "./types";
import type { DataAppSnapshot } from "./data/types";

export const demoSnapshot: WorkspaceSnapshot = {
  "root": "/Users/you/Lattice/Workspaces/First Look",
  "title": "First Look",
  "id": "0198-demo",
  "capabilities": [
    "pages",
    "canvas",
    "sqlite"
  ],
  "defaults": {
    "quickNoteDirectory": "Inbox",
    "archiveDirectory": "Archive"
  },
  "sourceTemplate": "demo",
  "directoryPurposes": {
    "Inbox": "Drop quick captures here — triage into Product or Research.",
    "Projects": "Active workstreams with a clear outcome.",
    "Product": "Product narrative, vision, and roadmap pages.",
    "Research": "Notes, comparisons, and diagrams.",
    "Notebooks": "Reserved for notebook resources.",
    "Canvases": "Spatial boards that link into workspace files.",
    "Data": "Tabular seeds and imported tables.",
    "Resources": "Ordinary files — JSON, YAML, code, images.",
    "Archive": "Finished or inactive material."
  },
  "manifestRevision": "demo:0",
  "resources": [
    {
      "path": "Home.md",
      "kind": "page"
    },
    {
      "path": "Archive",
      "kind": "folder"
    },
    {
      "path": "Canvases",
      "kind": "folder"
    },
    {
      "path": "Canvases/Product Strategy.canvas",
      "kind": "canvas"
    },
    {
      "path": "CRM.data",
      "kind": "data-app"
    },
    {
      "path": "Data",
      "kind": "folder"
    },
    {
      "path": "Data/sample.csv",
      "kind": "file",
      "formatId": "file:text"
    },
    {
      "path": "Inbox",
      "kind": "folder"
    },
    {
      "path": "Notebooks",
      "kind": "folder"
    },
    {
      "path": "Product",
      "kind": "folder"
    },
    {
      "path": "Product/Roadmap.md",
      "kind": "page"
    },
    {
      "path": "Product/Vision.md",
      "kind": "page"
    },
    {
      "path": "Projects",
      "kind": "folder"
    },
    {
      "path": "Research",
      "kind": "folder"
    },
    {
      "path": "Research/Architecture.md",
      "kind": "page"
    },
    {
      "path": "Research/Competitor Analysis.md",
      "kind": "page"
    },
    {
      "path": "Resources",
      "kind": "folder"
    },
    {
      "path": "Resources/config.json",
      "kind": "file",
      "formatId": "file:json"
    },
    {
      "path": "Resources/example.ts",
      "kind": "file",
      "formatId": "file:code"
    },
    {
      "path": "Resources/mark.svg",
      "kind": "file",
      "formatId": "file:text"
    },
    {
      "path": "Resources/notes.txt",
      "kind": "file",
      "formatId": "file:text"
    },
    {
      "path": "Resources/schema.yaml",
      "kind": "file",
      "formatId": "file:yaml"
    }
  ]
};

export const demoCanvas = {
  "nodes": [
    {
      "id": "intro",
      "type": "text",
      "x": 60,
      "y": 60,
      "width": 260,
      "height": 120,
      "text": "Sample canvas — double-click a file node to open it."
    },
    {
      "id": "vision",
      "type": "file",
      "file": "Product/Vision.md",
      "x": 360,
      "y": 60,
      "width": 220,
      "height": 120
    },
    {
      "id": "roadmap",
      "type": "file",
      "file": "Product/Roadmap.md",
      "x": 620,
      "y": 60,
      "width": 220,
      "height": 120
    }
  ],
  "edges": [
    {
      "id": "e1",
      "fromNode": "intro",
      "toNode": "vision"
    },
    {
      "id": "e2",
      "fromNode": "vision",
      "toNode": "roadmap"
    }
  ]
};

export const demoDataApp: DataAppSnapshot = {
  "title": "CRM",
  "default_table": "contacts",
  "package_revision": "demo:0",
  "columns": [
    {
      "name": "id",
      "field_type": "text",
      "sqlite_type": "TEXT"
    },
    {
      "name": "name",
      "field_type": "text",
      "sqlite_type": "TEXT"
    },
    {
      "name": "status",
      "field_type": "text",
      "sqlite_type": "TEXT"
    }
  ],
  "rows": [
    {
      "id": "0198-demo-ada-lovelace",
      "values": {
        "id": {
          "Text": "0198-demo-ada-lovelace"
        },
        "name": {
          "Text": "Ada Lovelace"
        },
        "status": {
          "Text": "Active"
        }
      }
    },
    {
      "id": "0198-demo-grace-hopper",
      "values": {
        "id": {
          "Text": "0198-demo-grace-hopper"
        },
        "name": {
          "Text": "Grace Hopper"
        },
        "status": {
          "Text": "Active"
        }
      }
    }
  ],
  "available_views": [
    "All"
  ],
  "active_view": "All",
  "layout_type": "grid",
  "filters": []
};

export const demoPages: Record<string, string> = {
  "Home.md": "---\ntitle: Home\n---\n\n# Home\n\nA sample Lattice workspace. Everything here is an ordinary file under a real\ndirectory — open it in any editor, or stay inside Lattice.\n\n## Try this\n\n1. Search with **⌘K** — pages are indexed by path and body.\n2. Open `Canvases/Product Strategy.canvas` — double-click a file node to jump.\n3. Capture a quick note with **⌘N** into `Inbox/`.\n4. Open `CRM.data` for a small typed table (contacts).\n5. Browse `Resources/` for JSON, YAML, TypeScript, and an SVG mark.\n6. Open [[Research/Architecture]] for a Mermaid diagram in a page.\n\n## Map\n\n| Path | Kind |\n| --- | --- |\n| [[Product/Vision]] | page |\n| [[Product/Roadmap]] | page |\n| [[Research/Competitor Analysis]] | page |\n| [[Research/Architecture]] | page (Mermaid) |\n| `Canvases/Product Strategy.canvas` | canvas |\n| `CRM.data` | data app |\n| `Data/sample.csv` | CSV file |\n| `Resources/` | code & config files |\n",
  "Product/Vision.md": "---\ntitle: Vision\n---\n\n# Vision\n\nA fast local workspace that treats documents, data, notebooks, and canvases as ordinary files.\n\nSee also [[Product/Roadmap]] and [[Research/Competitor Analysis]].\n",
  "Product/Roadmap.md": "---\ntitle: Roadmap\n---\n\n# Roadmap\n\n1. Daily-driver editing and search\n2. First data-app surface\n3. Capture from anywhere\n\nBack to [[Home]].\n",
  "Research/Competitor Analysis.md": "---\ntitle: Competitor Analysis\ntags: [research]\n---\n\n# Competitor Analysis\n\n| Tool | Keeps | Traps |\n| --- | --- | --- |\n| Obsidian | plain files | rich data |\n| Notion | interaction | your files |\n| Airtable | typed records | API lock-in |\n\n#research\n",
  "Research/Architecture.md": "---\ntitle: Architecture\ntags: [diagram]\n---\n\n# Architecture\n\nA tiny Mermaid sketch of how Lattice keeps the workspace honest:\n\n```mermaid\nflowchart LR\n  Files[Workspace files] --> Core[Rust command core]\n  Core --> UI[Desktop shell]\n  Core --> Index[Search index]\n  UI -->|semantic commands| Core\n```\n\nRelated: [[Product/Vision]] and [[Home]].\n"
};

export const demoTextFiles: Record<string, string> = {
  "Data/sample.csv": "name,role,status\nAda Lovelace,Analyst,Active\nGrace Hopper,Engineer,Active\n",
  "Resources/config.json": "{\n  \"name\": \"Personal\",\n  \"version\": 1,\n  \"features\": {\n    \"canvas\": true,\n    \"search\": true\n  }\n}\n",
  "Resources/schema.yaml": "title: Sample schema\nversion: 1\nfields:\n  - name: id\n    type: text\n  - name: status\n    type: text\n",
  "Resources/notes.txt": "Sample plain text file.\n\nThis fixture runs in the browser shell without native filesystem access.\n",
  "Resources/example.ts": "export function greet(name: string): string {\n  return `Hello, ${name}`;\n}\n",
  "Resources/mark.svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 32 32\" role=\"img\" aria-label=\"Lattice mark\">\n  <rect width=\"32\" height=\"32\" fill=\"#1a1a1a\"/>\n  <path fill=\"#e8a87c\" d=\"M8 22 L16 8 L24 22 Z\"/>\n</svg>\n"
};
