// GENERATED by scripts/compile-templates.mjs — do not edit.
export const GENERATED_TEMPLATE_CATALOG = [
  {
    "id": "personal",
    "order": 10,
    "name": "Personal",
    "category": "Everyday",
    "description": "Capture ideas, run projects, manage ongoing areas, and keep a durable library.",
    "visibility": "gallery",
    "recommended": true,
    "recommendedTitle": "Personal",
    "directories": [
      {
        "path": "Inbox",
        "purpose": "Drop raw captures here — triage them into Projects or Library."
      },
      {
        "path": "Projects"
      },
      {
        "path": "Areas"
      },
      {
        "path": "Library"
      },
      {
        "path": "Journal"
      },
      {
        "path": "Templates"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Welcome.md",
      "Inbox/",
      "Projects/",
      "Areas/",
      "Library/",
      "Journal/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox",
      "dailyNoteDirectory": "Journal",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md"
  },
  {
    "id": "project",
    "order": 20,
    "name": "Project",
    "category": "Work",
    "description": "Plan and deliver one outcome with decisions, research, working files, data, and outputs together.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Project",
    "directories": [
      {
        "path": "Decisions"
      },
      {
        "path": "Research"
      },
      {
        "path": "Working"
      },
      {
        "path": "Data"
      },
      {
        "path": "Outputs"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Brief.md",
      "Plan.md",
      "Decisions/",
      "Working/",
      "Data/",
      "Outputs/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Working",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md"
  },
  {
    "id": "research",
    "order": 30,
    "name": "Research",
    "category": "Knowledge & Research",
    "description": "Move from questions and sources through notes, experiments, analysis, and published outputs.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Research",
    "directories": [
      {
        "path": "Inbox"
      },
      {
        "path": "Sources"
      },
      {
        "path": "Notes"
      },
      {
        "path": "Data"
      },
      {
        "path": "Experiments"
      },
      {
        "path": "Outputs"
      },
      {
        "path": "Bibliography"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Questions.md",
      "Sources/",
      "Notes/",
      "Data/",
      "Experiments/",
      "Outputs/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite",
      "citations"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md"
  },
  {
    "id": "data-lab",
    "order": 40,
    "name": "Data Lab",
    "category": "Data & Advanced",
    "description": "Organize data sources, queries, notebooks, dashboards, reports, and reusable analysis.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Data Lab",
    "directories": [
      {
        "path": "Sources"
      },
      {
        "path": "Data"
      },
      {
        "path": "Queries"
      },
      {
        "path": "Notebooks"
      },
      {
        "path": "Dashboards"
      },
      {
        "path": "Reports"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Sources/",
      "Data/",
      "Queries/",
      "Notebooks/",
      "Dashboards/",
      "Reports/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite",
      "jupyter"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Reports",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md"
  },
  {
    "id": "blank",
    "order": 50,
    "name": "Blank",
    "category": "Data & Advanced",
    "description": "Start with only lattice.yaml and shape the workspace yourself.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Workspace",
    "directories": [],
    "preview": [
      "lattice.yaml"
    ],
    "capabilities": [
      "pages"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox"
    }
  },
  {
    "id": "demo",
    "order": 60,
    "name": "First Look",
    "category": "Sample",
    "description": "A curated sample with linked pages and a canvas for a quick first look.",
    "visibility": "sample",
    "recommended": false,
    "recommendedTitle": "First Look",
    "directories": [
      {
        "path": "Product"
      },
      {
        "path": "Research"
      },
      {
        "path": "Canvases"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Product/Vision.md",
      "Product/Roadmap.md",
      "Research/Competitor Analysis.md",
      "Canvases/Product Strategy.canvas"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Research",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md"
  },
  {
    "id": "team",
    "order": 90,
    "name": "Team",
    "category": "Work",
    "description": "Legacy shared-workspace scaffold retained for CLI compatibility.",
    "visibility": "legacy",
    "recommended": false,
    "recommendedTitle": "Team",
    "directories": [
      {
        "path": "Projects"
      },
      {
        "path": "Docs"
      },
      {
        "path": "Meetings"
      },
      {
        "path": "Research"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Projects/",
      "Docs/",
      "Meetings/",
      "Research/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Meetings",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md"
  }
] as const;
