// GENERATED by scripts/compile-templates.mjs — do not edit.
export const GENERATED_TEMPLATE_CATALOG = [
  {
    "id": "personal",
    "order": 10,
    "name": "Personal",
    "category": "Everyday",
    "description": "Capture ideas, run projects, manage ongoing areas, and keep a durable library.",
    "visibility": "gallery",
    "recommended": true,
    "recommendedTitle": "Personal",
    "directories": [
      {
        "path": "Inbox",
        "purpose": "Drop raw captures here — triage them into Projects or Library."
      },
      {
        "path": "Projects",
        "purpose": "Time-bound outcomes with a clear finish line."
      },
      {
        "path": "Areas",
        "purpose": "Ongoing responsibilities to maintain over time."
      },
      {
        "path": "Library",
        "purpose": "Reference material, book notes, and durable knowledge."
      },
      {
        "path": "Journal",
        "purpose": "Daily notes and periodic reflections."
      },
      {
        "path": "Templates",
        "purpose": "Reusable note patterns with {{title}} and {{date}} placeholders."
      },
      {
        "path": "Archive",
        "purpose": "Completed projects and inactive material."
      }
    ],
    "preview": [
      "Home.md",
      "Projects/Example Project.md",
      "Journal/{{date}}.md",
      "Templates/Daily.md",
      "Inbox/",
      "Projects/",
      "Journal/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox",
      "dailyNoteDirectory": "Journal",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "Tasks.data",
        "title": "Tasks",
        "table": "tasks",
        "columns": [
          {
            "name": "task",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "due",
            "type": "date"
          }
        ],
        "rows": [
          {
            "task": "Review inbox",
            "status": "todo",
            "due": null
          },
          {
            "task": "Plan the week",
            "status": "todo",
            "due": "2026-07-21"
          }
        ],
        "extraTables": [],
        "views": [],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "project",
    "order": 20,
    "name": "Project",
    "category": "Work",
    "description": "Plan and deliver one outcome with decisions, research, working files, data, and outputs together.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Project",
    "directories": [
      {
        "path": "Decisions",
        "purpose": "Lightweight ADRs and decision records."
      },
      {
        "path": "Meetings",
        "purpose": "Agendas, notes, and follow-ups from syncs."
      },
      {
        "path": "Research",
        "purpose": "Background reading and exploratory notes."
      },
      {
        "path": "Working",
        "purpose": "Active drafts and in-progress material."
      },
      {
        "path": "Data",
        "purpose": "Tables, datasets, and structured inputs."
      },
      {
        "path": "Outputs",
        "purpose": "Deliverables ready to share."
      },
      {
        "path": "Templates",
        "purpose": "Reusable patterns for decisions and meetings."
      },
      {
        "path": "Archive",
        "purpose": "Superseded or completed material."
      }
    ],
    "preview": [
      "Home.md",
      "Brief.md",
      "Plan.md",
      "Milestones.canvas",
      "Decisions/0001 Example decision.md",
      "Decisions/",
      "Meetings/",
      "Working/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Working",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": []
  },
  {
    "id": "writing",
    "order": 25,
    "name": "Writing",
    "category": "Work",
    "description": "Draft a manuscript with research, outlines, a style guide, and a submissions tracker beside the prose.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Writing",
    "directories": [
      {
        "path": "Manuscript",
        "purpose": "Chapters and long-form drafts, in reading order."
      },
      {
        "path": "Outlines",
        "purpose": "Story maps, beat sheets, and structural planning."
      },
      {
        "path": "Research",
        "purpose": "Background material, references, and fact-checking."
      },
      {
        "path": "Notes",
        "purpose": "Fragments, ideas, and scenes that have no home yet."
      },
      {
        "path": "Templates",
        "purpose": "Page templates with {{title}} and {{date}} placeholders."
      },
      {
        "path": "Archive",
        "purpose": "Cut scenes, abandoned drafts, and past versions."
      }
    ],
    "preview": [
      "Home.md",
      "Manuscript/Chapter 01.md",
      "Outlines/Story Map.canvas",
      "Style Guide.md",
      "Submissions.data",
      "Templates/Chapter.md",
      "Notes/",
      "Research/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Notes",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "Submissions.data",
        "title": "Submissions",
        "table": "submissions",
        "columns": [
          {
            "name": "piece",
            "type": "text"
          },
          {
            "name": "venue",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "submitted_on",
            "type": "date"
          },
          {
            "name": "response",
            "type": "long_text"
          }
        ],
        "rows": [
          {
            "piece": "Chapter 01 excerpt",
            "venue": "Example Quarterly",
            "status": "submitted",
            "submitted_on": "2026-07-01",
            "response": null
          },
          {
            "piece": "Flash piece",
            "venue": "Example Review",
            "status": "draft",
            "submitted_on": null,
            "response": "Polish the opening before sending."
          }
        ],
        "extraTables": [],
        "views": [],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "ops",
    "order": 27,
    "name": "Meetings & Ops",
    "category": "Work",
    "description": "Run meetings, one-on-ones, weekly reviews, and OKRs from one operational hub.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Ops",
    "directories": [
      {
        "path": "Meetings",
        "purpose": "Dated meeting notes — agendas, decisions, and follow-ups."
      },
      {
        "path": "1-1s",
        "purpose": "One page per person, appended over time."
      },
      {
        "path": "Reviews",
        "purpose": "Weekly and quarterly reviews of what actually happened."
      },
      {
        "path": "Templates",
        "purpose": "Page templates with {{title}} and {{date}} placeholders."
      },
      {
        "path": "Archive",
        "purpose": "Closed-out meetings and past cycles."
      }
    ],
    "preview": [
      "Home.md",
      "Meetings/{{date}} Kickoff.md",
      "OKRs.data",
      "Templates/Meeting Note.md",
      "Templates/Weekly Review.md",
      "Meetings/",
      "1-1s/",
      "Reviews/"
    ],
    "capabilities": [
      "pages",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Meetings",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "OKRs.data",
        "title": "OKRs",
        "table": "okrs",
        "columns": [
          {
            "name": "objective",
            "type": "text"
          },
          {
            "name": "key_result",
            "type": "text"
          },
          {
            "name": "owner",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "confidence",
            "type": "decimal"
          }
        ],
        "rows": [
          {
            "objective": "Ship the spring release",
            "key_result": "All launch blockers closed by the freeze date",
            "owner": "you",
            "status": "on-track",
            "confidence": 0.8
          },
          {
            "objective": "Ship the spring release",
            "key_result": "Two demo rounds with written findings",
            "owner": "you",
            "status": "at-risk",
            "confidence": 0.5
          },
          {
            "objective": "Grow the team sustainably",
            "key_result": "Every report has a current growth plan",
            "owner": "you",
            "status": "on-track",
            "confidence": 0.7
          }
        ],
        "extraTables": [],
        "views": [],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "research",
    "order": 30,
    "name": "Research",
    "category": "Knowledge & Research",
    "description": "Move from questions and sources through notes, experiments, analysis, and published outputs.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Research",
    "directories": [
      {
        "path": "Inbox",
        "purpose": "Unprocessed captures awaiting triage."
      },
      {
        "path": "Sources",
        "purpose": "Literature notes with citation metadata."
      },
      {
        "path": "Notes",
        "purpose": "Developing ideas and synthesis."
      },
      {
        "path": "Data",
        "purpose": "Datasets supporting analysis."
      },
      {
        "path": "Experiments",
        "purpose": "Reproducible runs and protocols."
      },
      {
        "path": "Outputs",
        "purpose": "Published findings and write-ups."
      },
      {
        "path": "Bibliography",
        "purpose": "Formal reference list and exports."
      },
      {
        "path": "Archive",
        "purpose": "Completed or superseded research."
      },
      {
        "path": "Templates",
        "purpose": "Page templates with {{title}} and {{date}} placeholders."
      }
    ],
    "preview": [
      "Home.md",
      "Questions.md",
      "Sources/Example Paper.md",
      "Sources/",
      "Notes/",
      "Experiments/",
      "Outputs/",
      "Templates/Literature Note.md"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite",
      "citations"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "Experiments/experiments-log.data",
        "title": "Experiments log",
        "table": "experiments",
        "columns": [
          {
            "name": "name",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "run_date",
            "type": "date"
          },
          {
            "name": "notes",
            "type": "long_text"
          }
        ],
        "rows": [
          {
            "name": "Baseline replication",
            "status": "planned",
            "run_date": null,
            "notes": "Replicate methods from Example Paper."
          },
          {
            "name": "Pilot run",
            "status": "complete",
            "run_date": "2026-07-10",
            "notes": "Smoke test of data pipeline."
          }
        ],
        "extraTables": [],
        "views": [],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "second-brain",
    "order": 35,
    "name": "Second Brain",
    "category": "Knowledge & Research",
    "description": "Capture fleeting ideas, grow atomic notes, and navigate your knowledge with maps of content and agent-ready context.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Second Brain",
    "directories": [
      {
        "path": "Inbox",
        "purpose": "Fleeting captures and unsorted inputs — triage into Notes or Sources."
      },
      {
        "path": "Notes",
        "purpose": "Atomic, densely linked notes that accrue meaning over time."
      },
      {
        "path": "MOCs",
        "purpose": "Maps of content that orient you across topics without rigid folders."
      },
      {
        "path": "Sources",
        "purpose": "Books, papers, articles, and media you want to cite or distill."
      },
      {
        "path": "Context",
        "purpose": "Workspace context for humans and agents — scope, tone, and conventions."
      },
      {
        "path": "Prompts",
        "purpose": "Reusable prompt patterns for synthesis, review, and extraction."
      },
      {
        "path": "Templates",
        "purpose": "Page templates with {{title}} and {{date}} placeholders."
      }
    ],
    "preview": [
      "MOCs/Knowledge Base.md",
      "Notes/Capture Workflow.md",
      "Notes/Evergreen Notes.md",
      "Notes/Linking Philosophy.md",
      "Inbox/",
      "Sources/",
      "Context/AGENTS.md",
      "Templates/Daily.md",
      "Prompts/"
    ],
    "capabilities": [
      "pages",
      "citations"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox",
      "templateDirectory": "Templates"
    },
    "openOnCreate": "MOCs/Knowledge Base.md",
    "dataPackages": []
  },
  {
    "id": "data-lab",
    "order": 40,
    "name": "Data Lab",
    "category": "Data & Advanced",
    "description": "Organize data sources, queries, notebooks, dashboards, reports, and reusable analysis.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Data Lab",
    "directories": [
      {
        "path": "Connections",
        "purpose": "Database, API, and file connection definitions."
      },
      {
        "path": "Data",
        "purpose": "Canonical datasets and curated tables."
      },
      {
        "path": "Queries",
        "purpose": "Reusable SQL and saved query definitions."
      },
      {
        "path": "Notebooks",
        "purpose": "Reproducible analysis notebooks."
      },
      {
        "path": "Dashboards",
        "purpose": "Interactive summaries and charts."
      },
      {
        "path": "Reports",
        "purpose": "Narrative findings and published analysis."
      },
      {
        "path": "Archive",
        "purpose": "Deprecated datasets and old reports."
      }
    ],
    "preview": [
      "Home.md",
      "Data/contacts.csv",
      "Queries/example.sql",
      "Notebooks/example.ipynb",
      "Connections/",
      "Data/",
      "Queries/",
      "Notebooks/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite",
      "jupyter"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Reports",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "Data/metrics.data",
        "title": "Metrics",
        "table": "metrics",
        "columns": [
          {
            "name": "metric",
            "type": "text"
          },
          {
            "name": "value",
            "type": "decimal"
          },
          {
            "name": "recorded_on",
            "type": "date"
          },
          {
            "name": "category",
            "type": "text"
          }
        ],
        "rows": [
          {
            "metric": "active_users",
            "value": 128,
            "recorded_on": "2026-07-01",
            "category": "Engagement"
          },
          {
            "metric": "query_latency_ms",
            "value": 42.5,
            "recorded_on": "2026-07-01",
            "category": "Performance"
          },
          {
            "metric": "active_users",
            "value": 142,
            "recorded_on": "2026-07-08",
            "category": "Engagement"
          },
          {
            "metric": "query_latency_ms",
            "value": 38.2,
            "recorded_on": "2026-07-08",
            "category": "Performance"
          },
          {
            "metric": "error_rate_pct",
            "value": 0.3,
            "recorded_on": "2026-07-08",
            "category": "Reliability"
          }
        ],
        "extraTables": [],
        "views": [
          {
            "name": "Board",
            "layout": "board",
            "group_by": "category",
            "columns": [
              "metric",
              "value",
              "category"
            ]
          },
          {
            "name": "Calendar",
            "layout": "calendar",
            "date_field": "recorded_on",
            "columns": []
          },
          {
            "name": "Gallery",
            "layout": "gallery",
            "cover_field": "metric",
            "columns": []
          },
          {
            "name": "Form",
            "layout": "form",
            "columns": []
          }
        ],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "dev-notebook",
    "order": 45,
    "name": "Dev Notebook",
    "category": "Work",
    "description": "Track architecture, decisions, snippets, runbooks, debug notes, and issues in one engineering workspace.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Dev Notebook",
    "directories": [
      {
        "path": "Architecture",
        "purpose": "System diagrams, canvases, and structural notes."
      },
      {
        "path": "Decisions",
        "purpose": "Architecture decision records and technical rationale."
      },
      {
        "path": "Snippets",
        "purpose": "Reusable TypeScript, Rust, SQL, and shell fragments.",
        "defaultKind": "file"
      },
      {
        "path": "Runbooks",
        "purpose": "Operational procedures, deploy steps, and incident playbooks."
      },
      {
        "path": "Debug Journal",
        "purpose": "Timestamped investigation notes, repro steps, and hypotheses."
      },
      {
        "path": "Templates",
        "purpose": "Page templates with {{title}} and {{date}} placeholders."
      },
      {
        "path": "Archive",
        "purpose": "Retired notes, resolved issues, and superseded decisions."
      }
    ],
    "preview": [
      "Home.md",
      "Architecture/System Overview.canvas",
      "Architecture/Component Map.md",
      "Decisions/0001-record-architecture-decisions.md",
      "Snippets/",
      "Runbooks/",
      "Issues.data",
      "Templates/Debug Session.md"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Debug Journal",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "Issues.data",
        "title": "Issues",
        "table": "issues",
        "columns": [
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "priority",
            "type": "text"
          },
          {
            "name": "component",
            "type": "text"
          },
          {
            "name": "notes",
            "type": "long_text"
          }
        ],
        "rows": [
          {
            "title": "Provision workspace from template",
            "status": "done",
            "priority": "medium",
            "component": "tooling",
            "notes": "Seed Issues.data and verify wiki links on Home.md."
          },
          {
            "title": "Add health check endpoint",
            "status": "open",
            "priority": "high",
            "component": "api",
            "notes": "See Snippets/api-handler.ts for the handler stub."
          },
          {
            "title": "Document deploy rollback",
            "status": "open",
            "priority": "low",
            "component": "ops",
            "notes": "Capture steps in Runbooks/ before the next release."
          }
        ],
        "extraTables": [],
        "views": [],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "blank",
    "order": 50,
    "name": "Blank",
    "category": "Data & Advanced",
    "description": "Start with only lattice.yaml and shape the workspace yourself.",
    "visibility": "gallery",
    "recommended": false,
    "recommendedTitle": "Workspace",
    "directories": [],
    "preview": [
      "lattice.yaml"
    ],
    "capabilities": [
      "pages"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox"
    },
    "dataPackages": []
  },
  {
    "id": "demo",
    "order": 60,
    "name": "First Look",
    "category": "Sample",
    "description": "Kitchen-sink sample: CRM + Delivery + Metrics + OKRs data apps, canvas, notebooks, hybrid search try-queries, voice/Quick Note tips, daemon runtime diagram, templates, and assorted files.",
    "visibility": "sample",
    "recommended": false,
    "recommendedTitle": "First Look",
    "directories": [
      {
        "path": "Inbox",
        "purpose": "Drop quick captures here — triage into Product or Research."
      },
      {
        "path": "Projects",
        "purpose": "Active workstreams with a clear outcome."
      },
      {
        "path": "Product",
        "purpose": "Product narrative, vision, principles, and roadmap pages."
      },
      {
        "path": "Research",
        "purpose": "Notes, comparisons, long reads, and diagrams."
      },
      {
        "path": "Notebooks",
        "purpose": "Reproducible analysis notebooks beside CRM and CSV seeds."
      },
      {
        "path": "Canvases",
        "purpose": "Spatial boards that link into workspace files."
      },
      {
        "path": "Templates",
        "purpose": "Page templates with {{title}} and {{date}} placeholders."
      },
      {
        "path": "Data",
        "purpose": "Tabular seeds and imported tables."
      },
      {
        "path": "Resources",
        "purpose": "Ordinary files — JSON, YAML, code, SQL, images."
      },
      {
        "path": "Archive",
        "purpose": "Finished or inactive material."
      }
    ],
    "preview": [
      "Home.md",
      "Research/Local Runtime.md",
      "Research/Long Read.md",
      "Product/Vision.md",
      "CRM.data",
      "Projects/Delivery.data",
      "Data/Metrics.data",
      "OKRs.data",
      "Canvases/Product Strategy.canvas",
      "Inbox/Sample capture.md",
      "Templates/Daily Note.md",
      "Notebooks/CRM exploration.ipynb",
      "Resources/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Inbox",
      "templateDirectory": "Templates",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": [
      {
        "path": "CRM.data",
        "title": "CRM",
        "table": "contacts",
        "columns": [
          {
            "name": "name",
            "type": "text"
          },
          {
            "name": "email",
            "type": "text"
          },
          {
            "name": "company",
            "type": "relation",
            "relation_table": "companies"
          },
          {
            "name": "due_date",
            "type": "date"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "notes",
            "type": "long_text"
          },
          {
            "name": "reports_to",
            "type": "relation",
            "relation_table": "contacts"
          }
        ],
        "rows": [
          {
            "name": "Ada Lovelace",
            "email": "ada@analytical.io",
            "company": [
              "Analytical Engines"
            ],
            "due_date": "2026-08-15",
            "status": "Active",
            "notes": "Champion for typed tables beside narrative docs."
          },
          {
            "name": "Grace Hopper",
            "email": "grace@navy.mil",
            "company": [
              "US Navy"
            ],
            "due_date": "2026-07-25",
            "status": "Active",
            "notes": "Asked for honest SQL export from CRM views.",
            "reports_to": [
              "Ada Lovelace"
            ]
          },
          {
            "name": "Alan Turing",
            "email": "alan@bletchley.uk",
            "company": [
              "Bletchley Park"
            ],
            "due_date": "2026-09-01",
            "status": "Nurture",
            "notes": "Interested after notebook preview ships."
          },
          {
            "name": "Katherine Johnson",
            "email": "katherine@nasa.gov",
            "company": [
              "NASA"
            ],
            "due_date": "2026-08-02",
            "status": "Active",
            "notes": "Needs calendar layout on due dates for standup.",
            "reports_to": [
              "Dorothy Vaughan"
            ]
          },
          {
            "name": "Dorothy Vaughan",
            "email": "dorothy@nasa.gov",
            "company": [
              "NASA"
            ],
            "due_date": null,
            "status": "Partner",
            "notes": "Coordinating team rollout; gallery view by company."
          },
          {
            "name": "Mary Jackson",
            "email": "mary@nasa.gov",
            "company": [
              "NASA"
            ],
            "due_date": "2026-07-30",
            "status": "Active",
            "notes": "Wants board grouped by status for sprint review.",
            "reports_to": [
              "Katherine Johnson"
            ]
          },
          {
            "name": "Tim Berners-Lee",
            "email": "tim@w3.org",
            "company": [
              "W3C"
            ],
            "due_date": "2026-10-12",
            "status": "Lead",
            "notes": "Linked data angle — follow up on wiki link semantics."
          },
          {
            "name": "Brendan Eich",
            "email": "brendan@mozilla.org",
            "company": [
              "Mozilla"
            ],
            "due_date": "2026-08-20",
            "status": "Nurture",
            "notes": "Curious about Tauri shell performance budgets."
          },
          {
            "name": "Margaret Hamilton",
            "email": "margaret@mit.edu",
            "company": [
              "MIT Instrumentation Lab"
            ],
            "due_date": "2026-07-22",
            "status": "Active",
            "notes": "Long-page scroll tests map to her reliability bar."
          },
          {
            "name": "Donald Knuth",
            "email": "knuth@stanford.edu",
            "company": [
              "Stanford"
            ],
            "due_date": null,
            "status": "Lead",
            "notes": "Literate programming — pages + code in Resources/."
          },
          {
            "name": "Linus Torvalds",
            "email": "linus@linux.foundation",
            "company": [
              "Linux Foundation"
            ],
            "due_date": "2026-11-05",
            "status": "Nurture",
            "notes": "Git-friendly workspace layout is the hook."
          },
          {
            "name": "Guido van Rossum",
            "email": "guido@python.org",
            "company": [
              "Python Software Foundation"
            ],
            "due_date": "2026-08-08",
            "status": "Active",
            "notes": "Notebook story — track under Notebooks/ when ready."
          },
          {
            "name": "Radia Perlman",
            "email": "radia@ieee.org",
            "company": [
              "IEEE"
            ],
            "due_date": "2026-09-18",
            "status": "Lead",
            "notes": "Spanning-tree metaphor for canvas + outline sync."
          },
          {
            "name": "Shafi Goldwasser",
            "email": "shafi@mit.edu",
            "company": [
              "MIT"
            ],
            "due_date": "2026-07-28",
            "status": "Active",
            "notes": "Security review of command preconditions.",
            "reports_to": [
              "Barbara Liskov"
            ]
          },
          {
            "name": "Barbara Liskov",
            "email": "liskov@mit.edu",
            "company": [
              "MIT"
            ],
            "due_date": null,
            "status": "Partner",
            "notes": "Substitution principle maps to resource adapters."
          },
          {
            "name": "Frances Allen",
            "email": "frances@ibm.com",
            "company": [
              "IBM Research"
            ],
            "due_date": "2026-08-30",
            "status": "Churned",
            "notes": "Paused — re-engage after perf benchmarks published."
          },
          {
            "name": "Edsger Dijkstra",
            "email": "edsger@utexas.edu",
            "company": [
              "UT Austin"
            ],
            "due_date": "2026-12-01",
            "status": "Lead",
            "notes": "Structured note templates under Templates/."
          },
          {
            "name": "Grace Brewster",
            "email": "grace.b@example.com",
            "company": [
              "Example Corp"
            ],
            "due_date": "2026-07-19",
            "status": "Lead",
            "notes": "Inbound from conference booth — assign owner."
          },
          {
            "name": "Leslie Lamport",
            "email": "lamport@microsoft.com",
            "company": [
              "Microsoft Research"
            ],
            "due_date": "2026-09-25",
            "status": "Nurture",
            "notes": "Formal methods audience — link Research/Architecture."
          },
          {
            "name": "Vint Cerf",
            "email": "vint@google.com",
            "company": [
              "Google"
            ],
            "due_date": "2026-10-01",
            "status": "Active",
            "notes": "Offline-first narrative resonates; wants demo workspace zip."
          }
        ],
        "extraTables": [
          {
            "table": "companies",
            "columns": [
              {
                "name": "name",
                "type": "text"
              }
            ],
            "rows": [
              {
                "name": "Analytical Engines"
              },
              {
                "name": "US Navy"
              },
              {
                "name": "Bletchley Park"
              },
              {
                "name": "NASA"
              },
              {
                "name": "W3C"
              },
              {
                "name": "Mozilla"
              },
              {
                "name": "MIT Instrumentation Lab"
              },
              {
                "name": "Stanford"
              },
              {
                "name": "Linux Foundation"
              },
              {
                "name": "Python Software Foundation"
              },
              {
                "name": "IEEE"
              },
              {
                "name": "MIT"
              },
              {
                "name": "IBM Research"
              },
              {
                "name": "UT Austin"
              },
              {
                "name": "Example Corp"
              },
              {
                "name": "Microsoft Research"
              },
              {
                "name": "Google"
              }
            ]
          }
        ],
        "views": [
          {
            "name": "Board",
            "layout": "board",
            "group_by": "status",
            "columns": [
              "name",
              "status"
            ]
          },
          {
            "name": "Calendar",
            "layout": "calendar",
            "date_field": "due_date",
            "columns": []
          },
          {
            "name": "Gallery",
            "layout": "gallery",
            "cover_field": "company",
            "columns": []
          },
          {
            "name": "Form",
            "layout": "form",
            "columns": []
          }
        ],
        "forms": [
          {
            "name": "ContactIntake",
            "table": "contacts",
            "fields": [
              "name",
              "email",
              "status",
              "company"
            ],
            "title": "Contact intake",
            "description": "Create a contact from the package form."
          }
        ],
        "interfaces": [
          {
            "name": "ContactOps",
            "views": [
              "Board"
            ],
            "forms": [
              "ContactIntake"
            ],
            "title": "Contact operations",
            "description": "Board view plus contact intake form for CRM canvas open."
          }
        ]
      },
      {
        "path": "Projects/Delivery.data",
        "title": "Delivery",
        "table": "items",
        "columns": [
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "owner",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "due",
            "type": "date"
          },
          {
            "name": "notes",
            "type": "long_text"
          }
        ],
        "rows": [
          {
            "title": "Native capture polish",
            "owner": "Will",
            "status": "Done",
            "due": "2026-07-18",
            "notes": "AVAudioEngine path landed; exercise mic in First Look."
          },
          {
            "title": "Hybrid search demo queries",
            "owner": "Will",
            "status": "In progress",
            "due": "2026-07-22",
            "notes": "Seed Local Runtime with glossary tokens."
          },
          {
            "title": "Phase 2 column designer",
            "owner": "TBD",
            "status": "Backlog",
            "due": "2026-08-15",
            "notes": "Wave 1 tables DAG — schema commands first."
          },
          {
            "title": "Quick Note dictation QA",
            "owner": "Will",
            "status": "In progress",
            "due": "2026-07-20",
            "notes": "Hold-to-dictate + silence discard."
          },
          {
            "title": "Canvas CRM subpaths",
            "owner": "Will",
            "status": "Done",
            "due": "2026-07-17",
            "notes": "Board/Gallery file nodes already wired."
          },
          {
            "title": "CSV type-review import",
            "owner": "TBD",
            "status": "Backlog",
            "due": null,
            "notes": "Promote Data/sample.csv after profiling lands."
          }
        ],
        "extraTables": [],
        "views": [
          {
            "name": "Board",
            "layout": "board",
            "group_by": "status",
            "columns": [
              "title",
              "owner",
              "status"
            ]
          },
          {
            "name": "Calendar",
            "layout": "calendar",
            "date_field": "due",
            "columns": []
          },
          {
            "name": "Form",
            "layout": "form",
            "columns": []
          }
        ],
        "forms": [
          {
            "name": "Intake",
            "table": "items",
            "fields": [
              "title",
              "owner",
              "status",
              "due"
            ],
            "title": "Delivery intake",
            "description": "Add a delivery item without opening the grid."
          }
        ],
        "interfaces": []
      },
      {
        "path": "Data/Metrics.data",
        "title": "Metrics",
        "table": "metrics",
        "columns": [
          {
            "name": "metric",
            "type": "text"
          },
          {
            "name": "value",
            "type": "decimal"
          },
          {
            "name": "recorded_on",
            "type": "date"
          },
          {
            "name": "category",
            "type": "text"
          }
        ],
        "rows": [
          {
            "metric": "warm_first_partial_ms",
            "value": 158.3,
            "recorded_on": "2026-07-10",
            "category": "Voice"
          },
          {
            "metric": "search_p95_ms",
            "value": 42,
            "recorded_on": "2026-07-12",
            "category": "Search"
          },
          {
            "metric": "crm_open_ms",
            "value": 120,
            "recorded_on": "2026-07-15",
            "category": "Data"
          },
          {
            "metric": "warm_first_partial_ms",
            "value": 149.1,
            "recorded_on": "2026-07-18",
            "category": "Voice"
          },
          {
            "metric": "search_p95_ms",
            "value": 38,
            "recorded_on": "2026-07-18",
            "category": "Search"
          },
          {
            "metric": "long_read_scroll_fps",
            "value": 58,
            "recorded_on": "2026-07-18",
            "category": "Editor"
          }
        ],
        "extraTables": [],
        "views": [
          {
            "name": "Board",
            "layout": "board",
            "group_by": "category",
            "columns": [
              "metric",
              "value",
              "category"
            ]
          },
          {
            "name": "Calendar",
            "layout": "calendar",
            "date_field": "recorded_on",
            "columns": []
          },
          {
            "name": "Gallery",
            "layout": "gallery",
            "cover_field": "metric",
            "columns": []
          },
          {
            "name": "Form",
            "layout": "form",
            "columns": []
          }
        ],
        "forms": [],
        "interfaces": []
      },
      {
        "path": "OKRs.data",
        "title": "OKRs",
        "table": "okrs",
        "columns": [
          {
            "name": "objective",
            "type": "text"
          },
          {
            "name": "key_result",
            "type": "text"
          },
          {
            "name": "owner",
            "type": "text"
          },
          {
            "name": "status",
            "type": "text"
          },
          {
            "name": "confidence",
            "type": "decimal"
          }
        ],
        "rows": [
          {
            "objective": "Ship local runtime",
            "key_result": "Daemon + hybrid search on main",
            "owner": "platform",
            "status": "on-track",
            "confidence": 0.9
          },
          {
            "objective": "Ship local runtime",
            "key_result": "Voice thin client + Quick Note dictate",
            "owner": "platform",
            "status": "on-track",
            "confidence": 0.85
          },
          {
            "objective": "Credible data apps",
            "key_result": "Schema commands + column designer",
            "owner": "data",
            "status": "at-risk",
            "confidence": 0.45
          },
          {
            "objective": "Credible data apps",
            "key_result": "Multiple .data fixtures in First Look",
            "owner": "data",
            "status": "on-track",
            "confidence": 0.8
          }
        ],
        "extraTables": [],
        "views": [
          {
            "name": "Board",
            "layout": "board",
            "group_by": "status",
            "columns": [
              "objective",
              "key_result",
              "status"
            ]
          },
          {
            "name": "Form",
            "layout": "form",
            "columns": []
          }
        ],
        "forms": [],
        "interfaces": []
      }
    ]
  },
  {
    "id": "team",
    "order": 90,
    "name": "Team",
    "category": "Work",
    "description": "Legacy shared-workspace scaffold retained for CLI compatibility.",
    "visibility": "legacy",
    "recommended": false,
    "recommendedTitle": "Team",
    "directories": [
      {
        "path": "Projects"
      },
      {
        "path": "Docs"
      },
      {
        "path": "Meetings"
      },
      {
        "path": "Research"
      },
      {
        "path": "Archive"
      }
    ],
    "preview": [
      "Home.md",
      "Projects/",
      "Docs/",
      "Meetings/",
      "Research/"
    ],
    "capabilities": [
      "pages",
      "canvas",
      "sqlite"
    ],
    "workspaceDefaults": {
      "quickNoteDirectory": "Meetings",
      "archiveDirectory": "Archive"
    },
    "openOnCreate": "Home.md",
    "dataPackages": []
  }
] as const;
